<div class="footer wrapper">
                <!-- TODO MAKE THIS DYNAMIC -->
                <div class="copyright">
                    <p>© 2014 HImalayan Corporation dba Himalayan Dog Chew. All Rights reserved.</p>
                </div>
                <div class="social">
                    <ul>
                        <li><a href=""><img src="<?php echo ASSET_URL.'images/icon-in.png'?>" alt=""></a></li>
                        <li><a href=""><img src="<?php echo ASSET_URL.'images/icon-pin.png'?>" alt=""></a></li>
                        <li><a href=""><img src="<?php echo ASSET_URL.'images/icon-you.png'?>" alt=""></a></li>
                        <li><a href=""><img src="<?php echo ASSET_URL.'images/icon-inst.png'?>" alt=""></a></li>
                        <li><a href=""><img src="<?php echo ASSET_URL.'images/icon-fb.png'?>" alt=""></a></li>
                        <li class="last"><a href=""><img src="<?php echo ASSET_URL.'images/icon-tw.png'?>" alt=""></a></li>
                    </ul>
                </div>

                <!-- TODO MAKE THIS DYNAMIC -->
                <div class="contact">
                    <ul>
                        <li>1 (855) 414 5153</li>
                        <li>|</li>
                        <li class="last">Info@HImalanDogChew.com</li>
                    </ul>
                </div>
            </div>
           </div>
        </div><!-- end of div class = 'body' -->
    </body>
</html>
