
<!-- TODO MAKE THIS DYNAMIC -->
<div class="header">
    <div class="wrapper">
        <div class="floatingMenu">
        </div>
        <div class="headerMain">
            <div class="nav">
                <ul>
                    <li class="mission"><a href="<?php echo URL.'pages/view/our-mission'?>">our mission</a></li>
                    <li class="about"><a href="<?php echo URL.'pages/view/about-us'?>">about us</a></li>
                    <li class="creation"><a href="<?php echo URL.'products/categories'?>">our creation</a></li>
                    <li class="find"><a href="find.html">find us</a></li>
                    <li class="contact"><a href="<?php echo URL.'contacts'?>">contact us</a></li>
                </ul>
            </div>
        <div class="logo">
            <a href="<?php echo URL?>"><img src="<?php echo ASSET_URL.LOGO?>" alt=""></a>
        </div>
        </div>
        <div class="bottomLine"></div>
    </div>
</div>
<div class="body">