<!-- <html>
<head>
<title>Home</title>


</head>
<body> -->

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
    <?php loadHelper('head');?>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Himalayan Dog Chew</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS CALLS -->
        <?php addCss('reset.css');?>
        <?php addCss('normalize.css');?> 
        <?php addCss('normalize.min.css');?> 
        <?php addCss('flexslider.css');?> 
        <?php addCss('style.css');?> 
        <?php addCss('main.css');?> 

        <!-- JS CALLS -->
        <?php addJS('jquery-1.11.1.js');?>
        <?php addJS('modernizr-2.6.2.js');?>
        <?php addJS('plugins.js');?>
        <?php addJS('jquery.flexslider.js');?>
        <?php addJS('validation.js');?>
        <?php addJS('main.js');?>
        <?php addJS('himalayan.js');?>




       <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
         <script>
        //     (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        //     function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        //     e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        //     e.src='//www.google-analytics.com/analytics.js';
        //     r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        //     ga('create','UA-XXXXX-X');ga('send','pageview');
        // </script>

    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
