
<div class="header">
<div class="floatingMenu">
        <ul class="nav">
        <li class="testimonials"><a href="<?php echo URL.'testimonials'?>">Testimonials</a></li>
        <li class="photogallery"><a href="<?php echo URL.'photogallery'?>">Photogallery</a></li>
        <?php if(!Session::isLoggedIn()):?>
            <li class="signin"><a href="<?php echo URL.'login'?>">Signin</a></li>
        <?php else:?>
            <li class="signin"><a href="<?php echo URL.'account'?>">CPanel</a></li>
        <?php endif;?>

        </ul>
        </div>
    <div class="wrapper">
        
        <div class="headerMain">
            <div class="nav">
                <ul>
                    <li class="mission"><a href="<?php echo URL.'pages/view/our-mission'?>">our mission</a></li>
                    <li class="about"><a href="<?php echo URL.'pages/view/about-us'?>">about us</a></li>
                    <li class="creation"><a href="<?php echo URL.'products/categories'?>">our creation</a></li>
                    <li class="find"><a href="<?php echo URL.'search'?>">find us</a></li>
                    <li class="contact"><a href="<?php echo URL.'contacts'?>">contact us</a></li>
                </ul>
            </div>
        <div class="logo">
            <a href="<?php echo URL?>"><img src="<?php echo ASSET_URL.LOGO?>" alt=""></a>
        </div>
        </div>
        <div class="bottomLine"></div>
    </div>
</div>
<script type="text/javascript">
var test;
    $(".nav ul li a").filter(function(){
        test = $(this).parent().attr('class');
    if(this.href == location.href.replace(/#.*/, ""))
    {
        test = $(this).parent().attr('class');
        $(this).parent().attr('id',test+'-active');
        return true;
    }
    else return false;
});
</script>
<div class="body">