<!-- <div class="header">
	<div class="top-links">
		<ul>
			<li><a href="<?php echo URL.'photogallery/view'?>">Photo Gallery</a></li>
			<li><a href="<?php echo URL.'user/login/'?>">Sign In</a></li>
		</ul>
	</div>
	<div class="top-menu">
		<ul>
			<li><a href="#">Our mission</a></li>
			<li><a href="#">About Us</a></li>
			<li><a href="#">Our Creation</a></li>
			<li><a href="#">Find Us</a></li>
			<li><a href="#">Contact Us</a></li>
		</ul>
		<div class="logo">
			<h1><img src="<?php echo URL.'assets/images/'.LOGO?>"></h1>
		</div>
	</div>
</div> -->

<div class="header">
    <div class="wrapper">
        <div class="floatingMenu">
        </div>
        <div class="headerMain">
            <div class="nav">
                <ul>
                    <li class="mission"><a href="<?php echo URL.'pages/view/our-mission'?>">our mission</a></li>
                    <li class="about"><a href="<?php echo URL.'pages/view/about-us'?>">about us</a></li>
                    <li class="creation"><a href="<?php echo URL.'products/categories'?>">our creation</a></li>
                    <li class="find"><a href="find.html">find us</a></li>
                    <li class="contact"><a href="<?php echo URL.'contacts'?>">contact us</a></li>
                </ul>
            </div>
        <div class="logo">
            <a href="<?php echo URL?>"><img src="<?php echo ASSET_URL.LOGO?>" alt=""></a>
        </div>
        </div>
        <div class="bottomLine"></div>
    </div>
</div>
<div class="body">