
<div class="page-wrapper">
	<div class="actions" style="margin-top:50px;margin-left:15%">
		<a class="button" href="<?php echo ADMIN_URL.'category/addnew'?>">ADD NEW CATEGORY </a>
	</div>
	<div class="page-form">
		<div class="page-head">
			<h3>Categories</h3>
		</div>
		<div class="form">
<div class="categories" style="clear:left">
<form method = "post" action = "http://rojan/himalayan/admin/category/test">
<?php echo $view_catagoryval; ?>
<input type="submit" value="Save Category Order"/>
</form>
</div>
</div>
</div>
</div>

<script>
$('.expand').click(function(){
	$(this).parent().parent().find('ul').slideToggle();
})
</script>