<div class="wrapper">
	<div class="account-menu">
		<ul class="clearfix">
			<li><a href="<?php echo URL.'account/pricing'?>">Pricing</a></li>
			<li><a href="<?php echo URL.'account/forms'?>">Forms</a></li>
<!-- 			<li><a href="#">Distributors</a></li>
 -->			<li><a href="<?php echo URL.'account/guarantee'?>">Guarantee</a></li>
			<li><a href="<?php echo URL.'account/shipping'?>">Shipping</a></li>
			<li><a href="<?php echo URL.'account/cpanel'?>">Control Panel</a></li>
			<li><a href="<?php echo URL.'account/logout'?>">Logout</a></li>
		</ul>
	</div>
