<div class="wrapper">
	<div class="account-menu">
		<ul class="clearfix">
			<li><a class="pricing" href="<?php echo URL.'account/pricing'?>">pricing</a></li>
			<li><a class="forms"href="<?php echo URL.'account/forms'?>">forms</a></li>
<!-- 			<li><a href="#">Distributors</a></li>
 -->			<li><a class="guarantee-menu" href="<?php echo URL.'account/guarantee'?>">guarantee</a></li>
			<li><a class="shipping-menu" href="<?php echo URL.'account/shipping'?>">shipping</a></li>
			<li><a class="cpanel" href="<?php echo URL.'account/cpanel'?>">control Panel</a></li>
			<li><a href="<?php echo URL.'account/logout'?>">logout</a></li>
		</ul>
	</div>
