<?php //loadView('account/account-menu.phtml');?>

<?php $form_line1 = getModel('configuration')->getConfigValue('form_line_1');?>

<?php $form_line2 = getModel('configuration')->getConfigValue('form_line_2');?>

<?php $sales_email = getModel('configuration')->getConfigValue('sales_email');?>

<script type="text/javascript">

	$('.account-menu ul li a.forms').addClass('active');

</script>

<div class="forms clearfix">

<h1><?php echo $form_line1?></h1>

<ul class="clearfix">

<?php foreach($view_forms as $form):?>

	<li><a href="<?php echo UPLOAD_URL.$form['form_file']?>" target="_blank"><?php echo $form['form_name']?></a></li>

<?php endforeach;?>

</ul>

<p><?php echo $form_line2?><a href="mailto:<?php echo $sales_email?>" target="_top"><?php echo $sales_email?></a></p>

</div>

</div>