<?php loadView('account/account-menu.phtml');?>
<?php $session = Session::getCurrentSession();
$role = getModel('customer')->getCustomerRole($session['user_id']);?>

<div class="pricing-products">
<ul class="slides">
<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/bag_blue.jpg'?>"/>
	<p class="product-name">HDC Blue</p>
	<div class="desc">
	<p>For Dogs Under 15lbs</p>
	<p>3 - 4 pieces | 359 cal</p>

<?php if($role != 'customer'):?>
	<p>Wholesale price: <span>$5.15</span></p>
	<p>Discounted price: <span>$5.00</span></p>
	<p>MSRP price: <span>$9.99</span></p>
<?php endif;?>

	</div>
	</div>
</li>
<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/bag_gray.jpg'?>"/>
	<p class="product-name">HDC Gray</p>
	<div class="desc">
	<p>For Dogs under 70 pounds</p>
	<p>1 Piece | 614 Cal</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price : $8.80</p>
	<p>Discounted Price :$8.60</p>
	<p>MSRP :$17.99</p>
<?php endif;?>

	</div>
	</div>
</li>
<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/bag_green.jpg'?>"/>
	<p class="product-name">HDC Green</p>
	<div class="desc">
	<p>For Dogs under 35 pounds</p>
	<p>1 Piece | 256 Cal</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :$4.15</p>
	<p>Discounted Price :	$4.00</p>
	<p>MSRP :	$7.99</p>
<?php endif;?>

	</div>
	</div>
</li>
<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/bag_red.jpg'?>"/>
	<p class="product-name">HDC Red</p>
	<div class="desc">
	<p>For Dogs under 55 pounds</p>
	<p>1 Piece | 359 Cal</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$5.15</p>
	<p>Discounted Price :	$5.00</p>
	<p>MSRP :	$9.99</p>
<?php endif;?>

	</div>
	</div>
</li>
<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/bag_yellow.jpg'?>"/>
	<p class="product-name">HDC Yellow</p>
	<div class="desc">
	<p>For Dogs under 65 pounds</p>
	<p>3 Pieces | 1,179 Cal</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$16.75</p>
	<p>Discounted Price :	$16.30</p>
	<p>MSRP :	$27.99</p>
<?php endif;?>

	</div>
	</div>
</li>

<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/seasoning.jpg'?>"/>
	<p class="product-name">HDC Seasoning</p>
	<div class="desc">
	<p>For all dog sizes</p>
	<p>2 oz bottle : 204 cal per bottle</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$1.85</p>
	<p>Discounted Price :	$1.75</p>
	<p>MSRP :	$3.99</p>
<?php endif;?>

	</div>
	</div>
</li>

<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/yaky_crunch.jpg'?>"/>
	<p class="product-name">Yaky Crunch</p>
	<div class="desc">
	<p>For all dog sizes</p>
	<p>1.25 Oz box: 75 - 80 Pieces | 1.5 - 2 Cal per treat</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$2.65</p>
	<p>Discounted Price :	$2.50</p>
	<p>MSRP :	$4.99</p>
<?php endif;?>

	<p>3 Oz box: 200 - 220 Pieces | 1.5 - 2 Cal per treat</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$5.95</p>
	<p>Discounted Price :	$5.65</p>
	<p>MSRP :	$11.99</p>
<?php endif;?>

	</div>
	</div>
</li>

<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/yaky_nuggets.jpg'?>"/>
	<p class="product-name">Yaky Nugget</p>
	<div class="desc">
	<p>For all dog sizes</p>
	<p>21 - 24 Pieces | 17 - 20 Cal per treat</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$2.65</p>
	<p>Discounted Price :	$2.50</p>
	<p>MSRP :	$4.99</p>
<?php endif;?>
	</div>
	</div>
</li>

<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/yPuff2.jpg'?>"/>
	<p class="product-name">Yaky Nugget</p>
	<div class="desc">
	<p>For all dog sizes</p>
	<p>12 - 13 Pieces | 16 - 18 Cal per treat</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$2.65</p>
	<p>Discounted Price :	$2.50</p>
	<p>MSRP :	$4.99</p>
<?php endif;?>
	</div>
	</div>
</li>

<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/yaky_stick_12_box.jpg'?>"/>
	<img src="<?php echo ASSET_URL.'images/yaky_stick_6_box.jpg'?>"/>
	<p class="product-name">Yaky Sticks - 12"</p>
	<div class="desc">
	<p>For Dogs under 50 pounds</p>
	<p>Box of 12 Pieces | 152 Cal</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$71.40/cs; $5.95/pc</p>
	<p>Discounted Price :	$69.00/cs; $5.75/pc</p>
	<p>MSRP :	$11.99/pc</p>
<?php endif;?>
	</div>

	<p class="product-name">Yaky Sticks - 6"</p>
	<div class="desc">
	<p>For Dogs under 25 pounds</p>
	<p>Box of 12 Pieces | 152 Cal</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$42.00/cs; $3.50/pc</p>
	<p>Discounted Price :	$40.50/cs; $3.35/pc</p>
	<p>MSRP :	$7.49/pc</p>
<?php endif;?>
	</div>
	</div>
</li>

<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/fruity_fruit_box.jpg'?>"/>
	<p class="product-name">Yaky Yam Fruity Fruit</p>
	<div class="desc">
	<p>For all dog sizes</p>
	<p>4.0 Oz box: 40 - 43 Pieces | 8 - 11 Cal per treat</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$1.85</p>
	<p>Discounted Price :	$1.75</p>
	<p>MSRP :	$3.99</p>
<?php endif;?>

	<p>14.0 Oz box: 140 - 146 Pieces | 8 - 11 Cal per treat</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$4.85</p>
	<p>Discounted Price :	$4.60</p>
	<p>MSRP :	$9.99</p>
<?php endif;?>

	</div>
	</div>
</li>

<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/lotsa_chicken_box.jpg'?>"/>
	<p class="product-name">Yaky Yam Lotsa Chicken</p>
	<div class="desc">
	<p>For all dog sizes</p>
	<p>4.0 Oz box: 40 - 43 Pieces | 8 - 11 Cal per treat</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$1.85</p>
	<p>Discounted Price :	$1.75</p>
	<p>MSRP :	$3.99</p>
<?php endif;?>

	<p>14.0 Oz box: 140 - 146 Pieces | 8 - 11 Cal per treat</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$4.85</p>
	<p>Discounted Price :	$4.60</p>
	<p>MSRP :	$9.99</p>
<?php endif;?>

	</div>
	</div>
</li>

<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/very_veggie_box.jpg'?>"/>
	<p class="product-name">Yaky Yam Very Veggie</p>
	<div class="desc">
	<p>For all dog sizes</p>
	<p>4.0 Oz box: 40 - 43 Pieces | 8 - 11 Cal per treat</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$1.85</p>
	<p>Discounted Price :	$1.75</p>
	<p>MSRP :	$3.99</p>
<?php endif;?>

	<p>14.0 Oz box: 140 - 146 Pieces | 8 - 11 Cal per treat</p>

<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$4.85</p>
	<p>Discounted Price :	$4.60</p>
	<p>MSRP :	$9.99</p>
<?php endif;?>

	</div>
	</div>
</li>

<li>
	<div class="product">
	<img src="<?php echo ASSET_URL.'images/POP_web_l.jpg'?>"/>
	<p class="product-name">Himalayan POP Display</p>
	<div class="desc">
	<p>Collection of all Himalayan Products</p>
<?php if($role != 'customer'):?>
	<p>Wholesale Price :	$545.50</p>
<?php endif;?>
	</div>
	</div>
</li>


</ul>
</div>

<!-- <div class="products-thumbs">
	<ul class="slides">
	<img src="<?php echo ASSET_URL.'images/bag_blue.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/bag_gray.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/bag_green.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/bag_red.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/bag_yellow.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/seasoning.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/yaky_crunch.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/yaky_nuggets.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/yPuff2.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/yaky_stick_6_box.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/fruity_fruit_box.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/lotsa_chicken_box.jpg'?>" width="100" height="100"/>
	<img src="<?php echo ASSET_URL.'images/very_veggie_box.jpg'?>" width="100" height="100"/>
	</ul>
</div> -->

<script>
$(document).ready(function(){
// $('.products-thumbs').flexslider({
// 	animation:"slide",
// 	asNavFor:".pricing-products",
// 	itemWidth:100,
// });

$('.pricing-products').flexslider({
    animation: "slide",
    controlNav:true,
    directionNav:true,
  });

      // $('.products-thumbs').flexslider({
      //   animation: "slide",
      //   controlNav: true,
      //   directionNav: true,
      //   animationLoop: false,
      //   slideshow: false,
      //   itemWidth: 200,
      //   itemHeight:200,
      //   itemMargin: 5,
      //   asNavFor: '.pricing-products'
      // });

      // $('.pricing-products').flexslider({
      //   animation: "slide",
      //   controlNav: true,
      //   directionNav: true,
      //   animationLoop: false,
      //   slideshow: false,
      //   itemWidth: 1000,
      //   sync: ".products-thumbs",
      // });
});
</script>