<?php require_once('system/recaptchalib.php');
$error = null;
?>
<div class="testimonials-form">
<form method = "post" action ="http://192.168.1.107/himalayan/testimonials/testimonialPost">
<input type="hidden" value="<?php echo date('Y-m-d H:i:s');?>" name="t_dt"/>
	<label for = "t_name">Name</label>
	<input type="text" name="t_name" class="input-box required"/>
	<label for = "t_email">Email</label>
	<input type="text" name="t_email" class="input-box required email-validation"/>
	<label for = "t_add">city & state</label>
	<input type="text" name="t_add" class="input-box required"/>
	<label for = "t_comment">testimonial</label>
	<input type="text" name="t_comment" class="input-box required"/>
	<?php echo recaptcha_get_html(CAPTCHA_PUBLIC_KEY, $error);?>
	<input type="submit" value="submit"/>
</form>
<a href="<?php echo URL.'testimonials/show'?>">See what people are saying about our creations</a>
</div>
<script>
$('.testimonials-form form').submit(function(){
	return $(this).validate('input-box');
});
</script>