<script>
 $('li.testimonials').addClass('active');
</script>
<!-- <div class="wrapper">
	<div class="testimonials">
	<ul>
	<?php foreach($view_testimonials as $testimonial):?>
	<li>
		<div class="testimonial">
		<p class="title"><span><?php echo $testimonial['t_name']?></span> from <span><?php echo $testimonial['t_add']?></span> on <span><?php echo date("M d, Y", strtotime($testimonial['t_dt']))?></span></p>
		<p><?php echo $testimonial['t_comment']?></p>
		</div>
	</li>
	<?php endforeach;?>
	</ul>
	<div class="pagination">
	<?php 
	$page = getParam('p');
	loadHelper('pagination');
	showPagination($page, $view_pagination_num, 'testimonialforum/show');
	?>
	</div>
	</div>
	<div class="add-testimonials">
	<a href="<?php echo URL.'testimonialforum/'?>" class="btn btn-blue">Add a Testimonial of your own</a>
	</div>
</div> -->
<?php echo count($view_testimonials);?>
<div class="wrapper">
	<div class="testimonials">
		<ul class="slides">
		<?php foreach($view_testimonials as $testimonial):?>
			<li>
				<div class="testimonial">
					<p class="title"><span><?php echo $testimonial['testimonial_name']?></span> from <span><?php echo $testimonial['testimonial_address']?></span> on <span><?php echo date("M d, Y", strtotime($testimonial['testimonial_date']))?></span></p>
					<p><?php echo $testimonial['testimonial']?></p>
					<div class="actions">
					<a href="#">Reply with quote</a>
					<a href="#">Comment</a>
					<p>Was this helpful?</p>
					<a href="#">Yes</a>
					<a href="#">No</a>
					</div>
				</div>
			</li>
		<?php endforeach?>
		</ul>
	</div>
	<div class="search-testimonial">
	<form method="get" action="<?php echo URL.'testimonialforum/search'?>">
	<fieldset>
	<input type = "text" class="required input-box" name="testimonial_search_query" <?php if(isset($_GET['testimonial_search_query'])){ ?> value="<?php echo $_GET['testimonial_search_query']; ?>"<?php }?>/>
	</fieldset>
	<fieldset>
	<input type="submit" value="search" class="btn btn-blue"/>
	</fieldset>
	</form>
	</div>
</div>

<script type="text/javascript">
	$('.testimonials').flexslider({
		animation: "slide",
		controlNav: false,
		directionNav: true,
		animationLoop: false,
		slideshow: false,
		prevText: "Previous",
		nextText: "Next",
		itemWidth:551,
	});
</script>