<div class="header">
	<div class="top-links">
		<ul>
			<li><a href="<?php echo URL.'photogallery/view'?>">Photo Gallery</a></li>
			<li><a href="<?php echo URL.'user/login/'?>">Sign In</a></li>
		</ul>
	</div>
	<div class="top-menu">
		<ul>
			<li><a href="#">Our mission</a></li>
			<li><a href="#">About Us</a></li>
			<li><a href="#">Our Creation</a></li>
			<li><a href="#">Find Us</a></li>
			<li><a href="#">Contact Us</a></li>
		</ul>
		<div class="logo">
			<h1><img src="<?php echo URL.'assets/images/'.LOGO?>"></h1>
		</div>
	</div>
</div>