<div class="footer wrapper">
                <div class="copyright">
                    <p><?php echo getModel('configuration')->getConfigValue('footer_text');?></p>
                </div>
                <div class="social">
                    <ul>
                        <li><a href="<?php echo getModel('configuration')->getConfigValue('linkedin_link');?>"><img src="<?php echo ASSET_URL.'images/icon-in.png'?>" alt="" target="_blank"></a></li>
                        <li><a href="<?php echo getModel('configuration')->getConfigValue('pininterest_link');?>"><img src="<?php echo ASSET_URL.'images/icon-pin.png'?>" alt="" target="_blank"></a></li>
                        <li><a href="<?php echo getModel('configuration')->getConfigValue('youtube_link');?>"><img src="<?php echo ASSET_URL.'images/icon-you.png'?>" alt="" target="_blank"></a></li>
                        <li><a href="<?php echo getModel('configuration')->getConfigValue('instagram_link');?>"><img src="<?php echo ASSET_URL.'images/icon-inst.png'?>" alt="" target="_blank"></a></li>
                        <li><a href="<?php echo getModel('configuration')->getConfigValue('facebook_link');?>"><img src="<?php echo ASSET_URL.'images/icon-fb.png'?>" alt="" target="_blank"></a></li>
                        <li class="last"><a href="<?php echo getModel('configuration')->getConfigValue('twitter_link');?>"><img src="<?php echo ASSET_URL.'images/icon-tw.png'?>" target="_blank"></a></li>
                    </ul>
                </div>

                <div class="contact">
                    <ul>
                        <li><?php echo getModel('configuration')->getConfigValue('telephone');?></li>
                        <li>|</li>
                        <li class="last"><a href="mailto:<?php echo getModel('configuration')->getConfigValue('general_email');?>" target="_top"><?php echo getModel('configuration')->getConfigValue('general_email');?></a></li>
                    </ul>
                </div>
            </div>
           </div>
        </div><!-- end of div class = 'body' -->
    </body>
</html>
