<script>
 $('li.testimonials-nav').addClass('active');
</script>
<!-- <div class="wrapper">
	<div class="testimonials">
	<ul>
	<?php foreach($view_testimonials as $testimonial):?>
	<li>
		<div class="testimonial">
		<p class="title"><span><?php echo $testimonial['t_name']?></span> from <span><?php echo $testimonial['t_add']?></span> on <span><?php echo date("M d, Y", strtotime($testimonial['t_dt']))?></span></p>
		<p><?php echo $testimonial['t_comment']?></p>
		</div>
	</li>
	<?php endforeach;?>
	</ul>
	<div class="pagination">
	<?php 
	$page = getParam('p');
	loadHelper('pagination');
	showPagination($page, $view_pagination_num, 'testimonialforum/show');
	?>
	</div>
	</div>
	<div class="add-testimonials">
	<a href="<?php echo URL.'testimonialforum/'?>" class="btn btn-blue">Add a Testimonial of your own</a>
	</div>
</div> -->
<div class="wrapper clearfix">
	<div class="new-testimonial-left">
		<div class="testimonials">
			<ul class="slides">
			<?php $count = 0;?>
			<?php foreach($view_testimonials as $testimonial):?>
				<li>
				  <div class="scroll scroll-<?php echo $count?>">
	                                <div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
	                                <div class="viewport" style="height:335px">
	                                <div class="overview">
					<div class="testimonial">
						<p class="title"><span><?php echo $testimonial['testimonial_name']?></span> from <span><?php echo $testimonial['testimonial_address']?></span> on <span><?php echo date("M d, Y", strtotime($testimonial['testimonial_date']))?></span></p>
						<p><?php echo $testimonial['testimonial']?></p>
						<div class="actions">
						<a href="#">reply with quote</a>
						<a href="javascript:;"> | </a>
						<a href="javascript:void(0)" class="comment-link">comment</a>
						<div class="helpfulornot">
						<input type="hidden" name="testimonial_id_actions" value="<?php echo $testimonial['testimonial_id']?>"/>
							<p>Was this helpful?</p>
							<a href="javascript:void(0)" class="helpful action"><span>yes!</span></a>
							<a href="javascript:void(0)" class="not-helpful action"><span>no</span></a>
						</div>
						</div>
						<div class="helpful-count">
						<p>This post has helped <?php echo $testimonial['testimonial_helpful_count']?> people so far!</p>
						</div>
					</div>
						<div class="comment-form" style="display:none">
	<!-- 					<form method="post" action="<?php echo URL.'testimonialforum/addComment'?>">
	 -->							<input type="hidden" class="t_id" name="comment_testimonial_id" value="<?php echo $testimonial['testimonial_id']?>"/>
								<input type="hidden" name="comment_from" value="user"/>
								<label for = "comment">Comment: </label>
								<textarea name="comment_message" id="comment-message" class="input-box required"></textarea>
	<!-- 							<input type="text" name="comment_message" class="input-box required editor"/>
	 -->							<input type="button" value="Add Comment" class="add-comment"/>
	<!-- 						</form>
	 -->					</div>
					<?php $comments = getModel('testimonials')->getTestimonialComments($testimonial['testimonial_id']);?>
					<div class="comments">
					<?php if($comments):?>
						
						<?php foreach($comments as $comment):?>
							<?php if($comment['comment_from'] == 'hdc'):?>
								<div class="comment_hdc">
									<?php echo $comment['comment_message']?>
								</div>
							<?php else:?>
								<div class="comment_user">
									<?php echo $comment['comment_message']?>
								</div>
							<?php endif;?>
						<?php endforeach;?>
						
					<?php endif;?>
					</div>
					</div>
					</div>
					<script type="text/javascript">
	                                $(document).ready(function(){
	                                    $('.scroll-<?php echo $count?>').tinyscrollbar();
	                                });
	                            </script>
	                            <?php $count++?>
				</li>
			<?php endforeach?>
			</ul>
		</div>
		 
		<script type="text/javascript">
		$('.comment-link').click(function(){$(this).parent().parent().parent().find('.comment-form').show(); $(window).resize()});
		$('.add-comment').click(function(){
			if($(this).parent().find('#comment-message').val())
			{
							$cf = $(this).parent().parent().parent().find('.comments');
			var id = $(this).parent().find('input[name=comment_testimonial_id]').val();
			var datas = {
				'comment_testimonial_id': $(this).parent().find('input[name=comment_testimonial_id]').val(),
				'comment_from': $(this).parent().find('input[name=comment_from]').val(),
				'comment_message': $(this).parent().find('#comment-message').val(),
			};
			console.log(datas);
			var urls = "<?php echo URL.'testimonialforum/addComment'?>";
			$.ajax({
				type:"POST",
				url:urls,
				data:datas,
				success:function(result){
						alert(1);
					$.get('<?php echo URL?>testimonialforum/loadComments/'+id, function(data){
						console.log(data);
						$cf.html(data);
						$(window).resize();
						$cf.parent().find('.comment-form').find("#comment-message").val('');
						
					});
				}

			});

			$(this).parent().find('.error').remove();
			}
			else
			{
				$(this).parent().append('<p class="error">Comment cannot be empty</p>');
			}
			
		});
		</script>
		<?php if(count($view_testimonials)>1):?>
		<div class="previous-next clearfix">
		<a href="javascript:void(0)" id="next" onclick="$('.flex-next').trigger('click')">next</a>
		<a href="javascript:void(0)" id="prev" onclick="$('.flex-prev').trigger('click')">previous</a>
		</div>
	<?php endif;?>
	</div>
	<div class="new-testimonial">
		<div class="search-testimonial">
		<form method="get" action="<?php echo URL.'testimonialforum/search'?>">
		<fieldset>
		<input type = "text" class="required input-box" name="testimonial_search_query" <?php if(isset($_GET['testimonial_search_query'])){ ?> value="<?php echo $_GET['testimonial_search_query']; ?>"<?php }?>/>
		</fieldset>
		<fieldset>
		<input type="submit" value="search" class="btn btn-blue"/>
		</fieldset>
		</form>
		</div>
		<div class="message">
		<p>As with any dog treat, please supervise your dog(s) when feeding our treats and be cautious to discard when any potential hazard presents itself. </p>
		<a href="<?php echo URL.'testimonialforum'?>" class="btn btn-blue">add your testimonial</a>
		</div>
	</div>
</div>

<script type="text/javascript">
	$('.testimonials').flexslider({
		animation: "slide",
		controlNav: false,
		directionNav: true,
		animationLoop: false,
		slideshow: false,
		prevText: "Previous",
		nextText: "Next",
		itemWidth:600,
	});
</script>
<script>
$('a.helpful').click(function(){
			var id = $(this).parent().find('input[name=testimonial_id_actions]').val();
			$a = $(this);
			console.log($a);
			$.ajax({
				url: '<?php echo URL?>testimonialforum/makehelpful/'+id,
				success:function(result)
				{
					if(result == 'true')
					{
						$('a.action').removeClass('active');
						$a.addClass('active');
					}
				}
			});
		});

$('a.not-helpful').click(function(){
			var id = $(this).parent().find('input[name=testimonial_id_actions]').val();
			$a = $(this);
			console.log($a);
			$.ajax({
				url: '<?php echo URL?>testimonialforum/nothelpful/'+id,
				success:function(result)
				{
					if(result == 'true')
					{
						$('a.action').removeClass('active');
						$a.addClass('active');
					}
				}
			});
		});
$('.flex-next').click(function(){
	$(window).resize();
});
</script>

	<script>
	$(document).ready(function(){


	});
	</script>

