<div class="page-wrapper">
<div class="actions">
  <a class="button" href="<?php echo ADMIN_URL.'photogallery/addnewphoto'?>">ADD NEW IMAGE </a>
</div>
<?php if(isset($view_gallery)){ ?>

<table class="grid">
  <tr>
    <th>Image</th>
    <th>Photo Caption</th>
    <th>Photo Status</th>
    <th>Delete </th>
  </tr>
  <?php foreach ($view_gallery as $view_gallery) { ?>
	

  <tr>
    <td><a href="<?php echo ADMIN_URL.'photogallery/editgallery/'.$view_gallery['photo_id']; ?>"><?php echo $view_gallery['photo_image']; ?></a></td>  
    <td><a href="<?php echo ADMIN_URL.'photogallery/editgallery/'.$view_gallery['photo_id']; ?>"><?php echo strip_tags(substr($view_gallery['photo_caption'],0,15)); ?></a></td>
    <td><a href="<?php echo ADMIN_URL.'photogallery/editgallery/'.$view_gallery['photo_id']; ?>"><?php echo $view_gallery['photo_status']; ?></a></td>
    <td><a class="button" href="<?php echo ADMIN_URL.'photogallery/deletegallery/'.$view_gallery['photo_id']; ?>" class="confirm">Delete</a></td>
  </tr> 

<?php } echo'</table>';}?>
<div class="pagination-bottom">
  <?php
$page = getParam('p');
if(!$page) $page = 1;
loadHelper('pagination');
showPagination($page, $view_pagination_num, 'admin/photogallery/index');
?>
</div>
<script>
$(document).ready(function(){
  $('.confirm').click(function(){
    var answer = confirm("Are you sure you want to delete this item?");
        if (answer){
            return true;
        } else {
            return false;
        }
  });
});
</script>