<a href="<?php echo ADMIN_URL.'attributes/add'?>">Add New Attribute</a>

<?php if(isset($view_attributes)):?>
	<table>
		<thead>
			<th>Attribute ID</th>
			<th>Attribute Code</th>
			<th>Attribute Name</th>
		</thead>
		<tbody>
			<?php foreach($view_attributes as $attribute):?>
				<tr>
					<td><a href="<?php echo ADMIN_URL.'attributes/edit/'.$attribute['aid']?>"><?php echo $attribute['aid']?></td>
					<td><a href="<?php echo ADMIN_URL.'attributes/edit/'.$attribute['aid']?>"><?php echo $attribute['acode']?></td>
					<td><a href="<?php echo ADMIN_URL.'attributes/edit/'.$attribute['aid']?>"><?php echo $attribute['aname']?></td>
				</tr>
			<?php endforeach;?>
		</tbody>
	</table>
<?php endif;?>