<div class="wrapper">
                <div class="policy">
                    <div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
                    <div class="viewport">
                        <div class="overview">
                        <?php Widget::render('web-usage');?>
                        </div>
                    </div>
                </div>
                <div class="policyButton">
                    <a href="<?php echo URL.'pages/privacypolicy'?>" class="btn btn-blue">Privacy Policy</a>
                    <a href="javascript:history.back()" class="btn btn-blue">back</a>
                </div>
            </div>

             <script type="text/javascript">
            $(document).ready(function(){
                $('.policy').tinyscrollbar();
            });
        </script>