<?php echo AdminSession::showErrorMessages();
echo AdminSession::showSuccessMessages();?>
<div class="page-wrapper">
<div class="actions">
	<a class="button" href="<?php echo ADMIN_URL.'products/add'?>">Add Product</a>
</div>
<?php if(isset($view_products)):?>
<?php loadHelper('view');?>
<table class="grid">
<thead>
	<th>Product ID</th>
	<th>Name</th>
	<th>SKU</th>
	<th>Type</th>
	<th>Attribute Set</th>
	<th>Quantity</th>
	<th>Status</th>
	<th>Action</th>
</thead>
<tbody>
<?php foreach($view_products as $product):?>
	<tr>
		<td><a href="<?php echo ADMIN_URL.'products/edit/'.$product['pid']?>"><?php echo $product['pid']?></a></td>
		<td><a href="<?php echo ADMIN_URL.'products/edit/'.$product['pid']?>"><?php echo $product['pname']?></a></td>
		<td><a href="<?php echo ADMIN_URL.'products/edit/'.$product['pid']?>"><?php echo $product['psku']?></a></td>
		<td><a href="<?php echo ADMIN_URL.'products/edit/'.$product['pid']?>"><?php echo getModel('products')->getTypeNameFromId($product['ptype'])?></a></td>
		<td><a href="<?php echo ADMIN_URL.'products/edit/'.$product['pid']?>"><?php echo getModel('attributeset')->getAttributeSetNameFromId($product['product_asid'])?></a></td>
		<td><a href="<?php echo ADMIN_URL.'products/edit/'.$product['pid']?>"><?php echo $product['quantity']?></a></td>
		<td><a class="button" href="<?php echo ADMIN_URL.'products/statusToggle/'.$product['pid']?>"><?php echo convertStatusIdToText($product['status'])?></a></td>
		<td><a class="button" href="<?php echo ADMIN_URL.'products/delete/'.$product['pid']?>" class="confirm">Delete</a></td>
	</tr>
<?php endforeach;?>
</tbody>
</table>
<div class="pagination-bottom">
<?php
$page = getParam('p');
if(!$page) $page = 1;
loadHelper('pagination');
showPagination($page, $view_pagination_num, 'admin/products/index');
?>
<?php endif;?>
</div>
<script>
$(document).ready(function(){
	$('.confirm').click(function(){
		var answer = confirm("Are you sure you want to delete this item?");
        if (answer){
            return true;
        } else {
            return false;
        }
	});
});
</script>

</div>