<?php loadHelper('inputs');?>
<?php $pid = getParam('pid');?>
<?php if($pid):?>
	<?php $associated = getModel('products')->getAssociatedProducts($pid);?>
	<?php if(($view_variations)):?>
	<ul>
	<?php foreach($view_variations as $variation):?>
	<li>
		<input type="checkbox" name="variations[]" value="<?php echo $variation['pid']?>" <?php echo (in_array($variation['pid'], $associated))?'checked':null?>/>
		<label for ="variations"><?php echo $variation['pname'];?></label>
		
	</li>
<?php endforeach;?>
</ul>
<?php else: ?>
	<h3>No Variations Found. Atleast one variation needs to be created</h3>
<?php endif;?>
<?php else:?>
	<?php if(($view_variations)):?>
	<ul>
	<?php foreach($view_variations as $variation):?>
	<li>
		<input type="checkbox" name="variations[]" value="<?php echo $variation['pid']?>"/>
			<label for ="variations"><?php echo $variation['pname'];?></label>
			
		</li>
	<?php endforeach;?>
<?php else: ?>
	<h3>No Variations Found. Atleast one variation needs to be created</h3>
<?php endif;?>
<?php endif;?>