<div class="wrapper">
<div class="loginform">
<div class="contactForm login-form">
<?php if (isset($view_verified)) { echo $view_verified; } else {?> 
<fieldset class="align-left">
<form action="<?php echo URL.'login/forgetpasswordprocess'?>" method="post">
Enter you email ID: <input type="text" name="email" class="input-box required email-validation"> 
<br><font color="red"><?php if(isset($view_notverified)) { echo $view_notverified; } ?></font></br>
 <button class="btn btn-blue" onclick="$('.login-form form').submit();">Submit</button>
</form>
</fieldset>
<?php } ?>
</div>
</div>
</div>

<script>
	$('.loginform form').submit(function(){
		return $(this).validate('input-box');
	});
</script>






<!--

<script>
 $('li.signin').addClass('active');
</script>
<div class="wrapper">
<div class="loginform">
<a href="<?php echo URL.'login/register'?>" class="btn btn-blue">join</a>
<div class="contactForm login-form">
<?php Session::showErrorMessages();?>
<form method = "post" action = "<?php echo URL.'login/loginto'?>">
<fieldset>		
<label for="username"><b>email</b></label>
<input type="text" name="username" size="40">
</fieldset>
<fieldset>
<label for="password"><b>password</b></label>
<input type="password" name="password" size="40">	
</fieldset> 
<fieldset class="align-right">
 <button class="btn btn-blue" onclick="$('.login-form form').submit();">sign in</button>
 <a href="<?php echo URL.'login/forgotpassword'; ?>" class="btn btn-blue">Forget Password </a>
</fieldset>
 </form> 
 </div>
 </div>
</div>
-->


