<?php

// /var_dump($_SESSION['token']); die();
//var_dump($_SESSION['token']); die();
//var_dump($view_check);
//var_dump(Session::getCurrentSession('alinaa'));

?>
<?php 
 //if(isset($view_loginchecks)){ echo $view_loginchecks; }

?>
<script>
 $('li.signin').addClass('active');
</script>
<div class="wrapper">
<div class="loginform">
<a href="<?php echo URL.'login/register'?>" class="btn btn-blue">join</a>
<div class="contactForm login-form">
<?php Session::showErrorMessages();?>
<form method = "post" action = "<?php echo URL.'login/loginto'?>">
<fieldset>		
<label for="username"><b>email</b></label>
<input type="text" name="username" size="40">
</fieldset>
<fieldset>
<label for="password"><b>password</b></label>
<input type="password" name="password" size="40">	
</fieldset> 
<fieldset class="align-right">
 <button class="btn btn-blue" onclick="$('.login-form form').submit();">sign in</button>
</fieldset>
 </form>
 </div>
 </div>
</div>

