<?php

// /var_dump($_SESSION['token']); die();
//var_dump($_SESSION['token']); die();
//var_dump($view_check);
//var_dump(Session::getCurrentSession('alinaa'));

?>
<?php 
 //if(isset($view_loginchecks)){ echo $view_loginchecks; }

?>
<div class="wrapper">
<a href="<?php echo URL.'login/register'?>" class="btn btn-blue">Sign Up</a>
<?php Session::showErrorMessages();?>
<div class="contactForm login-form">
<form method = "post" action = "<?php echo URL.'login/loginto'?>">
<fieldset>		
<label for="username">Email</label>
<input type="text" name="username" size="40">
</fieldset>
<fieldset>
<label for="password">Password</label>
<input type="password" name="password" size="40">	
</fieldset> 
<fieldset class="align-right">
 <button class="btn btn-blue" onclick="$('.login-form form').submit();">Signin</button>
</fieldset>
 </form>
 </div>
</div>

