<?php

// /var_dump($_SESSION['token']); die();
//var_dump($_SESSION['token']); die();
//var_dump($view_check);
//var_dump(Session::getCurrentSession('alinaa'));

?>
<?php 
 //if(isset($view_loginchecks)){ echo $view_loginchecks; }

?>

<a href="<?php echo URL.'login/register'?>">Sign Up</a>
<form method = "post" action = "<?php echo URL.'login/loginto'?>">		
Email <br><input type="text" name="username" size="40"><br>
 Password <br><input type="password" name="password" size="40"><br>
 <input type="submit" value = "Signin"/>
 </form>


