	<?php Session::showErrorMessages();?>
	<?php $states = getModel('customer')->getAllStates();?>
	<div class="wrapper signup clearfix">
		<div class="register-choice">
		<label></label>
		<input type="radio" class="registration css-checkbox" name="registration-type" checked id="registration-consumer"/><label  for = "registration-consumer" class="css-label radGroup1 radGroup2">consumer</label>
		<input type="radio" class="registration css-checkbox" name="registration-type" id="registration-retailer"/><label  for = "registration-retailer" class="css-label radGroup1 radGroup2">retailer</label>
		

		</div>
		<div class="register-retailer-form" style="display:none">
			<form method = "post" action = "<?php echo URL.'login/registerPost'?>">
				<div class="half">
					<fieldset>
					<label for ="name">name</label>
					<input type="text" class="input-box required text-validation" name="mname"/>
					</fieldset>
					<fieldset>
					<label for ="name">email</label>
					<input type="text" class="input-box required email-validation" name="memail"/>
					</fieldset>
					<fieldset>
					<label for ="name">password</label>
					<input type="password" class="input-box required text-validation" name="mpass"/>
					</fieldset>
					<fieldset>
					<label for ="name">address</label>
					<input type="text" class="input-box required text-validation" name="madd"/>
					</fieldset>
					<fieldset>
					<label for ="name">apt/ste</label>
					<input type="text" class="input-box text-validation" name="madd2"/>
					</fieldset>
					<fieldset>
					<label for ="name">city</label>
					<input type="text" class="input-box required text-validation" name="mcity"/>
					</fieldset>
					<fieldset>
					<label for ="name">state</label>
					<select name="mstate" class="input-box" style="width:64%;height: 46px;border: none;border-radius: 10px;">
						<?php foreach($states as $state):?>
							<option value="<?php echo $state['abb']?>"><?php echo $state['stt_nm']?></option>
						<?php endforeach;?>
					</select>
					<!-- <input type="text" class="input-box required text-validation" name="mstate"/> -->
					</fieldset>
					<fieldset>
					<label for ="name">zip</label>
					<input type="text" class="input-box required zip-validation" name="mzip"/>
					</fieldset>
				</div>
				<div class="half">
					<fieldset>
					<label for ="name">phone</label>
					<input type="text" class="input-box required phone-validation" name="mtel"/>
					</fieldset>
					<fieldset>
					<label for ="name">fax</label>
					<input type="text" class="input-box required fax-validation" name="mfax"/>
					</fieldset>
					<fieldset>
					<label for ="name">company/store</label>
					<input type="text" class="input-box required text-validation" name="mcompany"/>
					</fieldset>
					<fieldset>
					<label for ="name">website</label>
					<input type="text" class="input-box required text-validation" name="mwebsite"/>
					</fieldset>
					<!-- <label for ="name">Website</label>
					<input type="text" class="input-box required text-validation" name="mein"/>
					 -->
					 <fieldset>
					<label for ="name">EIN(tax ID)</label>
					<input type="text" class="input-box required ein-validation" name="mein"/>
					</fieldset>
					<fieldset>
					<label></label>
					<input type="hidden" value="retailer" name="mtype"/>
					<input type="checkbox" class="input-box required css-checkbox" checkboxname="privacy-policy" id="checkboxG1"/><label for="checkboxG1" class="css-label radGroup1">I have read the <a href="<?php echo URL.'pages/privacypolicy'?>">Privacy Policy</a> and <a href="<?php echo URL.'pages/webusage'?>">Web Usage Agreement</a></label>
					</fieldset>
					<fieldset>
					<label></label>
					<input type="submit" value="Submit" class="btn btn-blue" />
					</fieldset>
				</div>
				
				

			</form>
		</div>


	<div class="register-consumer-form">
		<form method = "post" action = "<?php echo URL.'login/registerPost'?>">
			<div class="half">
				<fieldset>
				<label for ="name">name</label>
				<input type="text" class="input-box required text-validation" name="mname"/>
				</fieldset>
				<fieldset>
				<label for ="name">email</label>
				<input type="text" class="input-box required email-validation" name="memail"/>
				</fieldset>
				<fieldset>
				<label for ="name">password</label>
				<input type="password" class="input-box required text-validation" name="mpass"/>
				</fieldset>
				<fieldset>
				<label for ="name">address</label>
				<input type="text" class="input-box required text-validation" name="madd"/>
				</fieldset>
				<fieldset>
				<label for ="name">apt/ste</label>
				<input type="text" class="input-box text-validation" name="madd2"/>
				</fieldset>
			</div>
			<div class="half">
				<fieldset>
				<label for ="name">city</label>
				<input type="text" class="input-box required text-validation" name="mcity"/>
				</fieldset>
				<fieldset>
				<label for ="name">state</label>
				<select name="mstate" class="input-box" style="width:64%;height: 46px;border: none;border-radius: 10px;">
						<?php foreach($states as $state):?>
							<option value="<?php echo $state['abb']?>"><?php echo $state['stt_nm']?></option>
						<?php endforeach;?>
					</select>
				<!-- <input type="text" class="input-box required text-validation" name="mstate"/> -->
				</fieldset>
				<fieldset>
				<label for ="name">zip</label>
				<input type="text" class="input-box required zip-validation" name="mzip"/>
				</fieldset>
				<fieldset>
				<label for ="name">phone</label>
				<input type="text" class="input-box required phone-validation" name="mtel"/>
				</fieldset>
				<fieldset>
				<label for ="name">fax</label>
				<input type="text" class="input-box fax-validation" name="mfax"/>
				</fieldset>
				<!-- <fieldset>
				<label for ="name">Company/store</label>
				<input type="text" class="input-box required text-validation" name="mcompany"/>
				</fieldset> -->
				<!-- <label for ="name">Website</label>
				<input type="text" class="input-box required text-validation" name="mein"/>
				 -->
				<!--  <fieldset>
				<label for ="name">EIN(tax ID)</label>
				<input type="text" class="input-box required text-validation" name="mein"/>
				</fieldset> -->
				<fieldset>
				<label></label>
				<input type="hidden" value="customer" name="mtype"/>
				<input type="checkbox" class="input-box required css-checkbox" checkboxname="privacy-policy" id="checkboxG2"/><label for="checkboxG2" class="css-label radGroup1">I have read the <a href="<?php echo URL.'pages/privacypolicy'?>">Privacy Policy</a> and <a href="<?php echo URL.'pages/webusage'?>">Web Usage Agreement</a></label>
				</fieldset>
				<fieldset>
				<label></label>
				<input type="submit" value="Submit" class="btn btn-blue" />
				</fieldset>
			</div>
			
			
		</form>

	</div>
	</div>
	<script>
	$('.register-retailer-form form').submit(function(){
		return $(this).validate('input-box');
	});
	$('.register-consumer-form form').submit(function(){
		return $(this).validate('input-box');
	});



	jQuery(document).ready(function(){
				//showRegistrationForm();
				jQuery('.registration').click(function(){
					showRegistrationForm();
				});
			});
			function showRegistrationForm()
			{
			
				if(jQuery('#registration-retailer').is(':checked')) 
				{ 
					jQuery('.register-consumer-form').hide();
					jQuery('.register-retailer-form').show(); 
				}
				else
				{
					jQuery('.register-retailer-form').hide();
					jQuery('.register-consumer-form').show();		
				}
			
			}
	</script>