<div class="wrapper home-wrapper">
<div class="leftBody half">
	<h1>Our Mission&nbsp;</h1>
<p>Himalayan Corporation aspires to become the most prominient company in the pet industry while maintainin and building on our reputation for innovative, healthy, and high quality products. to ensure we uphold these standards in each new enterp[rise, we are driven by a set of core values:</p>
<ul>
<li>Provide exceptional customer service</li>
<li>Treat employees with the utmost respect</li>
<li>Produce and sell products of the highest quality</li>
<li>Maximize savings, satisfaction and value for our customers</li>
<li>Fuel growth through customer referrals, Innovation and reputation</li>
<li>Actively impact the community through our presence and charitable contributions</li>
</ul>
<p>Himalayan Corporation embodies a collection of divers pet products with the highest aspirations.</p>
<h1>Our Vision</h1>
<p>is to be recognized and respected for producin the healthiest and highest quality pet food and products in teh world.</p></div>
<div class="rightBody">
<div class="announcements">
	<div class="annoucement-header product-list-header">
	<h2>the barking bulletin</h2>
	</div>
	<div class="announcement">
		<p>Dear Dog Lovers:<br /><br />We are devastated to learn the losses of so many dogs from taking the treats from China in the recent years. Our heart, prayers and solidarity are with the families who lost their dogs, the families who have dogs as their pets, and families who have pets.<br /><br />Product of highest quality and confidence should be the most essential priority of any product manufacturer. We, at Himalayan, strive to bring such products in the market, and put all efforts to ensure that none of the ingredients and packaging materials is from China. We continue to procure our products from the USA and Nepal only, as we have in the past.<br /><br />Please contact <a href="mailto:info@himalayandogchew.com">info@himalayandogchew.com</a> if you have any questions, concerns or suggestions.<br /><br />Sujan Kumar Shrestha<br />Chairman &amp; CEO</p>	</div>
</div>
</div>
<div class="home-slider">
<ul class="slides">
<li>
	<img src="<?php echo UPLOAD_URL.'cms/home/homepage-banner.png'?>"/>
</li>
</ul>
</div>

</div>

<script type="text/javascript">
	
      $('.home-slider').flexslider({
        animation: "slide",
        controlNav: false,
        directionNav: false,
        animationLoop: true,
        slideshow: true,
      });
</script>