<script type="text/javascript">
	$('.nav ul li.mission').attr('id','mission-active');
</script>
<div class="wrapper home-wrapper">
<div class="leftBody half">
<?php Widget::render('mission_vision');?>
<?php $images = array();?>
<?php foreach (glob("assets/uploads/cms/home/*.*") as $image)
		{
			array_push($images, $image);
		}
?>
</div>
<div class="rightBody">
<div class="announcements">
	<div class="annoucement-header product-list-header">
	<h2>the barking bulletin</h2>
	</div>
	<div class="announcement">
	<?php Widget::render('announcement');?>
	</div>
</div>
</div>
<div class="home-slider">
<ul class="slides">
<li>
	<img src="<?php echo URL.$image?>"/>
</li>
</ul>
</div>

</div>

<script type="text/javascript">
	
      $('.home-slider').flexslider({
        animation: "slide",
        controlNav: false,
        directionNav: false,
        animationLoop: true,
        slideshow: true,
      });
</script>