<script type="text/javascript">
	$('.nav ul li.mission').attr('id','mission-active');
</script>
<div class="wrapper home-wrapper">
<div class="clearfix" style="position:relative;">
<div class="half">
<?php Widget::render('mission_vision');?>
<?php $images = array();?>
<?php foreach (glob("assets/uploads/cms/home/*.*") as $image)
		{
			array_push($images, $image);
		}
?>
</div>
<div class="half bulletin">
<div class="announcements">
	<div class="annoucement-header product-list-header">
	<h2><?php echo getModel('configuration')->getConfigValue('barking-bulletin-header');?></h2>
	</div>
	<div class="announcement scroll">
	<div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
        <div class="viewport">
	        <div class="overview">
<!-- 	        <h2>Total Organizations</h2>
	        <p>that we've donated to this year:<br>for humans: <span class="organization-count">3</span><br>for animals: <span class="organization-count">51</span></p>
 -->
 			<div class="organizations">
 			<?php Widget::render('organization-count');?>
 			</div>
 			<?php
	 			$monthNum  = 10;
				$monthName = date('M', mktime(0, 0, 0, $monthNum, 1));
 			?>
 			<div class="events">
				<h2>Upcoming Events</h2>
				<?php $events = getModel('events')->getAllEvents();?>
				<?php foreach($events as $event):?>
					<div class="event">
					<?php if($event['eventDateBegin'] != '0000-00-00' and $event['eventDateEnd'] != '0000-00-00'):?>
						<?php $startDate = $event['eventDateBegin']; $endDate = $event['eventDateEnd'];?>
						<?php $startDate = explode('-',$startDate); $endDate = explode('-',$endDate);?>
						<?php $startMonth = date('F', mktime(0, 0, 0, $startDate[1], 1)); $endMonth = date('F', mktime(0, 0, 0, $endDate[1], 1));?>
						<?php $startDay = $startDate[2]; $endDay = $endDate[2];?>
						<p class="event-date"><?php echo $startMonth.' '.$startDay.' - '.$endMonth.' '.$endDay;?>
					<?php else :?>
						<?php if($event['eventDateBegin'] != '0000-00-00'):?>
							<?php $startDate = $event['eventDateBegin'];?>
							<?php $startDate = explode('-',$startDate);?>
							<?php $startMonth = date('F', mktime(0, 0, 0, $startDate[1], 1));?>
							<?php $startDay = $startDate[2];?>
							<p class="event-date"><?php echo $startMonth.' '.$startDay;?>
						<?php endif;?>
					<?php endif;?>
<!-- 					<p class="event-date"><?php echo $event['eventDateBegin'];?></p>
 -->					<p class="event-name"><?php echo $event['eventName'];?></p>
					<p class="event-address"><?php echo $event['eventAddress'];?></p>
					</div>
				<?php endforeach;?>
 				<!-- <div class="event">
		 			<p class="event-date">October 2</p>
		 			<p class="event-name">Animal Supply Open House</p>
		 			<p class="event-address">Tacoma, WA</p>
	 			</div>
	 			<div class="event">
		 			<p class="event-date">October 16-17</p>
		 			<p class="event-name">Lone Pet Supply Open House</p>
		 			<p class="event-address">Houston, TX</p>
	 			</div> -->

 			</div>
			<?php //Widget::render('announcement');?>
			</div>
		</div>
	</div>
</div>
</div>
</div>
<div class="home-slider">
<ul class="slides">
<?php foreach (glob("assets/uploads/cms/home/*.*") as $image):?>
<li>
	<img src="<?php echo URL.$image?>"/>
</li>
<?php endforeach;?>
</ul>
</div>

</div>

<script type="text/javascript">
	
      $('.home-slider').flexslider({
        animation: "fade",
        controlNav: false,
        directionNav: false,
        animationLoop: true,
        slideshow: true,
        slideshowSpeed: 8000,
      });
</script>
<script type="text/javascript">
                                $(document).ready(function(){
                                    $('.scroll').tinyscrollbar();
                                });
                            </script>