<div class="page-wrapper">
<div class="actions">
	<a class="button" href="<?php echo ADMIN_URL.'pages/add'?>">Add New Page</a>
</div>
<?php loadHelper('view');
if(isset($view_pages)):?>
<table>
	<thead>
		<th>Page Title</th>
		<th>Url Key</th>
		<th width="12.5%">Status</th>
		<th width="12.5%">Action</th>
	</thead>
	<tbody>
		<?php foreach($view_pages as $page):?>
			<tr>
				<td><a href="<?php echo ADMIN_URL.'pages/edit/'.$page['page_id']?>"><?php echo $page['title']?></a></td>
				<td><a href="<?php echo ADMIN_URL.'pages/edit/'.$page['page_id']?>"><?php echo $page['urlKey']?></a></td>
				<td><a class="button" href="<?php echo ADMIN_URL.'pages/edit/'.$page['page_id']?>"><?php echo convertStatusIdToText($page['status']);?></a></td>
				<td><a class="button" href="<?php echo URL.'pages/view/'.$page['urlKey']?>" target = "_blank">Preview</a></td>
			</tr>
		<?php endforeach?>
	</tbody>
</table>
<div class="pagination-bottom">
<?php
$page = getParam('p');
if(!$page) $page = 1;
loadHelper('pagination');
showPagination($page, $view_pagination_num, 'admin/pages/index');
?>
</div>
<?php endif;?>
</div>