<?php echo AdminSession::showErrorMessages();
echo AdminSession::showSuccessMessages();?>

<?php loadHelper('view');?>

<?php if(!isset($view_page)):?>
<div class="addpage-form">
<form method = "post" action = "<?php echo ADMIN_URL.'pages/addpost'?>">
<label for ="title">Title</label>
<input type="text" name="title" class="input-box required text-validation"/>
<label for ="urlKey">URL Key</label>
<input type="text" name="urlKey" class="input-box required text-validation"/>
<label for="status">Status</label>
<select name="status">
	<option value="0"><?php echo convertStatusIdToText(0);?></option>
	<option value="1"><?php echo convertStatusIdToText(1);?></option>	
</select>

<label for="content">Content</label>
<a class="btn" href="javascript:void(0)" onclick="  tinymce.execCommand('mceRemoveControl', true, 'content');"><span>Toggle TinyMCE</span></a>
<textarea id='add' name="content" class="editor" id="content"></textarea>

<input type="submit" value="save"/>
</form>
</div>
<script>
$('form').submit(function(){
	return $(this).validate('input-box');
});
</script>
<?php else:?>
<form method = "post" action = "<?php echo ADMIN_URL.'pages/editpost'?>">
<input type="hidden" value="<?php echo $view_page['page_id']?>" name="page_id"/>
<label for ="title">Title</label>
<input type="text" name="title" class="input-box required text-validation" value="<?php echo $view_page['title']?>"/>
<label for ="urlKey">URL Key</label>
<input type="text" name="urlKey" class="input-box required text-validation" value="<?php echo $view_page['urlKey']?>"/>
<label for="status">Status</label>
<select name="status">
	<option value="0" <?php echo ($view_page['status'] == 0)?'selected':null?>><?php echo convertStatusIdToText(0);?></option>
	<option value="1" <?php echo ($view_page['status'] == 1)?'selected':null?>><?php echo convertStatusIdToText(1);?></option>	
</select>

<label for="content">Content</label>
<a href="javascript:void(0)" onclick="toggleEditor('edit')"><span>Toggle TinyMCE</span></a>
<textarea id='edit' name="content" class="editor"><?php echo $view_page['content']?></textarea>

<input type="submit" value="save"/>
</form>
<?php endif;?>
