<div class="page-wrapper">
<div class="actions">
<a class="button" href="<?php echo ADMIN_URL.'events/addnewEvent'?>">ADD NEW EVENTS </a>
</div>
<?php //var_dump($view_eventlist); die(); ?>
<?php if(isset($view_eventlist)){ ?>


<table class="grid">
  <tr>
    <th>Event Name</th>
    <th>Event Begins On</th>
    <th>Events Ends In </th> 
    <th>Events Description</th> 
    <th>Events Url</th>
    <th> Delete </th>
  </tr>
  <?php foreach ($view_eventlist as $view_eventlist) { ?>
	

  <tr>
    <td><a href="<?php echo ADMIN_URL.'events/editEvent/'.$view_eventlist['event_id']; ?>"><?php echo $view_eventlist['eventName']; ?></a></td>
    <td><a href="<?php echo ADMIN_URL.'events/editEvent/'.$view_eventlist['event_id']; ?>"><?php echo $view_eventlist['eventDateBegin']; ?></a></td>
    <td><a href="<?php echo ADMIN_URL.'events/editEvent/'.$view_eventlist['event_id']; ?>"><?php echo $view_eventlist['eventDateEnd']; ?></a></td>
    <td><a href="<?php echo ADMIN_URL.'events/editEvent/'.$view_eventlist['event_id']; ?>"><?php echo strip_tags(substr($view_eventlist['eventDesc'],0,15));  //$view_eventlist['eventDesc']; ?></a></td>
    <td><a href="http://<?php echo $view_eventlist['eventUrl']; ?>"><?php echo $view_eventlist['eventUrl']; ?></a></td>
<!--     <td><a href="<?php echo ADMIN_URL.'events/editEvent/'.$view_eventlist['event_id']; ?>">View More</a></td>
 -->
     <td><a class="button" href="<?php echo ADMIN_URL.'events/deleteEvent/'.$view_eventlist['event_id']; ?>" class="confirm">Delete</a>
    </td>  
  </tr> 

<?php } echo'</table>';}?>
<div class="pagination-bottom">
  <?php
$page = getParam('p');
if(!$page) $page = 1;
loadHelper('pagination');
showPagination($page, $view_pagination_num, 'admin/events/index');
?>
</div>
<script>
$(document).ready(function(){
  $('.confirm').click(function(){
    var answer = confirm("Are you sure you want to delete this item?");
        if (answer){
            return true;
        } else {
            return false;
        }
  });
});
</script>