<div class="page-wrapper">
<div class="actions">
<a class="button" href="<?php echo ADMIN_URL.'faq/add'?>">Add New FAQ</a>
</div>
<?php if(isset($view_faqs)):?>
<table class="grid">
	<thead>
		<th>FAQ ID</th>
		<th>FAQ Question</th>
		<th width="12.5%">Actions</th>
	</thead>
	<tbody>
		<?php foreach($view_faqs as $faq):?>
			<tr>
				<td><a href="<?php echo ADMIN_URL.'faq/edit/'.$faq['faq_id']?>"><?php echo $faq['faq_id']?></a></td>
				<td><a href="<?php echo ADMIN_URL.'faq/edit/'.$faq['faq_id']?>"><?php echo $faq['faq_question']?></a></td>
				<td><a class="button" href="<?php echo ADMIN_URL.'faq/delete/'.$faq['faq_id']?>">Delete</a></td>
			</tr>
		<?php endforeach;?>
	</tbody>
</table>
<div class="pagination-bottom">
<?php
$page = getParam('p');
if(!$page) $page = 1;
loadHelper('pagination');
showPagination($page, $view_pagination_num, 'admin/faq/index');
?>
</div>
<?php endif;?>
</div>