<div class="page-wrapper">
<div class="actions">
  <a class="button" href="<?php echo ADMIN_URL.'widgets/addnewWidgets'?>">Create New Widget</a>
 </div>
<?php //var_dump($view_eventlist); die(); ?>
<?php if(isset($view_widgetlist)){ ?>

<table>
  <tr>
    <th>Widget Name</th>
    <th>Widget Title</th>
    <th>Widget Content </th> 
    <th>Widget Identifier</th> 
    <th width="12.5%"> Delete </th>
  </tr>
  <?php foreach ($view_widgetlist as $view_widgetlist) { ?>
	

  <tr>
    <td><a href="<?php echo ADMIN_URL.'widgets/editWidget/'.$view_widgetlist['widget_id']; ?>"><?php echo $view_widgetlist['widget_name']; ?></a></td>
    <td><a href="<?php echo ADMIN_URL.'widgets/editWidget/'.$view_widgetlist['widget_id']; ?>"><?php echo $view_widgetlist['widget_title']; ?></a></td>
    <td><a href="<?php echo ADMIN_URL.'widgets/editWidget/'.$view_widgetlist['widget_id']; ?>"><?php echo strip_tags(substr($view_widgetlist['widget_content'],0,15)); //$view_widgetlist['widget_content']; ?></a></td>
    <td><a href="<?php echo ADMIN_URL.'widgets/editWidget/'.$view_widgetlist['widget_id']; ?>"><?php echo $view_widgetlist['widget_identifier']; ?></a></td>
    <td><a class="button" href="<?php echo ADMIN_URL.'widgets/deleteWidget/'.$view_widgetlist['widget_id']; ?>" class="confirm">Delete</a>
    </td>  
  </tr> 

<?php } ?>
</table>
<script>
$(document).ready(function(){
  $('.confirm').click(function(){
    var answer = confirm("Are you sure you want to delete this item?");
        if (answer){
            return true;
        } else {
            return false;
        }
  });
});
</script>
<?php }?>
