<?php $back_to_creations = getModel('configuration')->getConfigValue('back_to_creation');?>
<div class="wrapper creationDetail">
	<div class="dog-chews microwave">
		<div class="leftBody">
			<div class="description">
			<?php if($view_url != 'nuggets'):?>
				<h1><?php echo Widget::getTitle('microwave');?></h1>
				<?php Widget::render('microwave');?>
			<?php else:?>
				<h1><?php echo Widget::getTitle('microwave_nugget');?></h1>
				<?php Widget::render('microwave_nugget');?>
			<?php endif;?>
			</div>
			<a class="btn btn-blue" href="<?php echo URL.'products/list/'.$view_url?>"> &lt; back</a>
		</div>
		<div class="rightBody">
			<div class="product-list-header clearfix">
				<span class="right"><a href="<?php echo URL.'products/categories'?>"><?php echo $back_to_creations?></a></span>
			</div>

			<div class="products">
				<ul class="slides">
					<li>
						<div class="product">
							<iframe width="627" height="368" src="<?php echo getModel('configuration')->getConfigValue('end-pieces-video')?>" frameborder="0"></iframe>		
							<div class="category-detail clearfix">
								<p class="test"></p>
							</div>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>