<div class="admin-header">
	<ul>
	<li><a href="<?php echo ADMIN_URL.'pages'?>">Pages</a></li>
	<li><a href="javascript:void(0)">Catalog</a>
		<ul>
			<li><a href="<?php echo ADMIN_URL.'attributes'?>">Manage Attributes</a></li>
			<li><a href="<?php echo ADMIN_URL.'attributeset'?>">Manage Attribute Sets</a></li>
			<li><a href="<?php echo ADMIN_URL.'category'?>">Manage Categories</a></li>
			<li><a href="<?php echo ADMIN_URL.'products'?>">Manage Products</a></li>
		</ul>
	</li>
	</ul>
</div>