<!-- <html>
<head>
<title>Home</title>


</head>
<body> -->

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
    <?php loadHelper('head');?>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Himalayan Dog Chew</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS CALLS -->
        <?php addCss('reset.css');?>
        <?php addCss('normalize.css');?> 
        <?php addCss('croppic.css');?> 
        <?php addCss('normalize.min.css');?> 
        <?php addCss('flexslider.css');?> 
        <?php addCss('style.css');?> 
        <?php addCss('main.css');?> 

        <!-- JS CALLS -->
        <?php addJS('jquery-1.11.1.js');?>
        <?php addJS('modernizr-2.6.2.min.js');?>
        <?php addJS('plugins.js');?>
        <?php addJS('jquery.flexslider.js');?>
        <?php addJS('validation.js');?>
        <?php addJS('tiny_mce/tiny_mce.js');?>
        <?php addJS('croppic.js');?>
        <?php addJS('main.js');?>
        <?php addJS('himalayan.js');?>



       <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
         <script>
        //     (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        //     function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        //     e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        //     e.src='//www.google-analytics.com/analytics.js';
        //     r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        //     ga('create','UA-XXXXX-X');ga('send','pageview');
        // </script>

        <script type="text/javascript">
    tinyMCE.init({
        // General options
        selector: "textarea.editor",
        editor_deselector : "test",
        theme : "advanced",
        plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,visualblocks",

        // Theme options
        theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,visualblocks",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        // Example content CSS (should be your site CSS)
        content_css : "css/content.css",

        // Drop lists for link/image/media/template dialogs
        template_external_list_url : "lists/template_list.js",
        external_link_list_url : "lists/link_list.js",
        external_image_list_url : "lists/image_list.js",
        media_external_list_url : "lists/media_list.js",

        // Style formats
        style_formats : [
            {title : 'Bold text', inline : 'b'},
            {title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
            {title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
            {title : 'Example 1', inline : 'span', classes : 'example1'},
            {title : 'Example 2', inline : 'span', classes : 'example2'},
            {title : 'Table styles'},
            {title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
        ],

       
    });
</script>

<script>
    var editorMode = true;
    function toggleEditor(id)
    {
        //alert();
        if(tinymce.get(id))
        {
            tinyMCE.execCommand('mceRemoveControl', false, id);
            editorMode = false;
        }
        else
        {
            tinyMCE.execCommand('mceAddControl', false, id);
            editorMode = true;

        }
    }

</script>


<script>
var tinyMCEmode = true; 

function toogleEditorMode(sEditorID) { 
    try { 
        if(tinyMCEmode) { 
            tinyMCE.removeMCEControl(tinyMCE.getEditorId(sEditorID)); 
            tinyMCEmode = false; 
        } else { 
            tinyMCE.addMCEControl(document.getElementById('editor'), sEditorID); 
            tinyMCEmode = true; 
        } 
    } catch(e) { 
        //error handling 
    }
    } 
</script>

    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
