<!-- <html>
<head>
<title>Home</title>


</head>
<body> -->

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
    <?php loadHelper('head');?>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Himalayan Dog Chew</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS CALLS -->
        <?php addCss('reset.css');?>
        <?php addCss('normalize.css');?> 
        <?php addCss('croppic.css');?> 
        <?php addCss('normalize.min.css');?> 
        <?php addCss('colorbox/colorbox.css')?>
        <?php addCss('flexslider.css');?> 
        <?php addCss('style.css');?> 
        <?php addCss('multifileupload.css');?> 
        <?php addCss('admin.css');?> 

        <!-- JS CALLS -->
        <?php addJS('jquery-1.11.1.js');?>
        <?php addJS('modernizr-2.6.2.min.js');?>
        <?php addJS('plugins.js');?>
        <?php addJS('jquery.flexslider.js');?>
        <?php addJS('colorbox/jquery.colorbox.js')?>
        <?php addJS('validation_admin.js');?>
        <?php addJS('tinymce/tinymce.js');?>
        <?php addJS('croppic.js');?>
        <?php addJS('multifileupload.js');?>
        <?php addJS('main.js');?>
        <?php addJS('himalayan.js');?>


       <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
         <script>
        //     (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        //     function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        //     e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        //     e.src='//www.google-analytics.com/analytics.js';
        //     r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        //     ga('create','UA-XXXXX-X');ga('send','pageview');
        // </script>



         <script type="text/javascript">
tinymce.init({
    selector: ".editor",theme: "modern",
   height:400,
    plugins: [
         "advlist autolink link image lists charmap print preview hr anchor pagebreak",
         "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking",
         "table contextmenu directionality emoticons paste textcolor responsivefilemanager code"
   ],
   toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect,formatselect,fontselect,fontsizeselect",
   fontsize_formats: "8pt 9pt 10pt 11pt 12pt 13pt 26pt 36pt",
   toolbar2: "| responsivefilemanager | link unlink anchor | image media | forecolor backcolor  | print preview code ",
   image_advtab: true ,
   external_filemanager_path:"<?php echo ASSET_URL.'js/filemanager/'?>",
   filemanager_title:"Responsive Filemanager" ,
   external_plugins: { "filemanager" : "/assets/js/filemanager/plugin.min.js"}
 });


//alina edit



</script>

    </head>
    <body>
    <div class="container">
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->