<div class="page-wrapper">
<div class="actions">
	<a class="button" href="<?php echo ADMIN_URL.'attributeset/add'?>">Add New Attribute Set</a>
</div>
<?php if(isset($view_attribute_set)):?>
	<table>
		<thead>
			<th>Attribute Set ID</th>
			<th>Attribute Set Code</th>
			<th>Attribute Set Name</th>
			<th>Actions</th>
		</thead>
		<tbody>
			<?php foreach($view_attribute_set as $attributeset):?>
				<tr>
					<td><a href="<?php echo ADMIN_URL.'attributeset/edit/'.$attributeset['asid']?>"><?php echo $attributeset['asid']?></td>
					<td><a href="<?php echo ADMIN_URL.'attributeset/edit/'.$attributeset['asid']?>"><?php echo $attributeset['ascode']?></td>
					<td><a href="<?php echo ADMIN_URL.'attributeset/edit/'.$attributeset['asid']?>"><?php echo $attributeset['asname']?></td>
					<td><a class="button" href="<?php echo ADMIN_URL.'attributeset/delete/'.$attributeset['asid']?>">Delete</td>
				</tr>
			<?php endforeach;?>
		</tbody>
	</table>
	<div class="pagination-bottom">
	<?php
$page = getParam('p');
if(!$page) $page = 1;
loadHelper('pagination');
showPagination($page, $view_pagination_num, 'admin/attributeset/index');
?>
</div>
<?php endif;?>
</div>