<?php echo AdminSession::showErrorMessages();
echo AdminSession::showSuccessMessages();
?>

<form method="post" action="<?php echo (!isset($view_attribute_set))?ADMIN_URL.'attributeset/addpost':ADMIN_URL.'attributeset/editpost'?>">
	<?php if(isset($view_attribute_set)):?>
		<input type="hidden" name="attribute_set_id" value="<?php echo $view_attribute_set['asid']?>"/>
	<?php endif;?>
	<label for ="ascode">Attribute Set Code</label>
	<input type="text" name="ascode" value="<?php echo (isset($view_attribute_set))?$view_attribute_set['ascode']:null?>"/>

	<label for ="asname">Attribute Set Name</label>
	<input type="text" name="asname" value="<?php echo (isset($view_attribute_set))?$view_attribute_set['asname']:null?>"/>

	<label for = 'attributes'>Select Attributes</label>
	<?php $attributes = getModel('attribute')->getAllAttributes();?>
	<select name="attributes[]" multiple	>
		<?php foreach($attributes as $attribute):?>
			<option value = "<?php echo $attribute['aid']?>" <?php echo (isset($view_attributes) and in_array($attribute['aid'], $view_attributes))?'selected':null?>><?php echo $attribute['aname']?></option>
		<?php endforeach;?>
	</select>
	<input type ="submit" value="Save"/>
</form>