<script>
 $('li.find').addClass('active');
 $('li.find').attr('id','find-active');
</script>
<div class="wrapper">

<div class="store-search-result">
<div class="dummy">
  </div>
<table class="mainBody2" cellspacing="0" cellpadding="0">
<tr>
    <!-- ********************************

    Left Pane 

    **************************************--> 

	<td align="left" valign="top" width="464" >
  
   <div class="scroll">
    <div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
                                <div class="viewport" style="height:355px">
                                <div class="overview">

		<?php echo (isset($view_search)?$view_search:null); ?>
    </div>
    </div>
	 </td>
   <script>
    var html = $('.search-title').html();
    $('.search-title').remove();
    $('.dummy').html('<div class="actual-search-title">'+html+"</div>");
    if($('.actual-search-title').text() == 'undefined') $('.actual-search-title').parent().remove();
   </script>


 	<td align="left" valign="top" style="padding: 0px 10px 0px 0px;" width="380" >

		<?php //include ("$pgms/consumer/consumerright.php"); ?>


		<!---------------------------------------consuemer right start---------------------------------------------->
		<table border="0" cellspacing="0" cellpadding="0" width="100%">
		<tr>
        <td valign="top"  class="" style="">
        <div class="productInfoM">
        <div class="productInfoM2" style="padding: 25px 25px 25px 25px;">  
          <!--&raquo;<a href="<?php echo URL."search/?input=consumers"; ?>" class="productLink">Consumer Information Home</a>
        <br /><br> 
		<?php if(!isset($_SESSION['user']))
				echo "&raquo; <a href=\"login/register\" class=\"productLink\">Register for Information &amp; mailing List</a>";
		?>
		<br><br> -->
		<div class="productInfo2">
        <form name="findStores" method="post" action="<?php echo URL.'searchnew/?input=consumers'?>">
        <input type="text" name="requestZipCode" size="4"  value="<?php if(isset($view_submitval)){ echo $view_submitval; } else {?>enter store name, city, state, province, or zip/postal code<?php } ?>" 
         style="background-color:white; 
             
              padding: 3px 3px 3px 15px;
              font-size:12px; 
              width:308px;
              vertical-align:9px;color:#bbb" 
              onfocus="if(this.value == 'enter store name, city, state, province, or zip/postal code') {
              this.value = '';
              this.style.color='#000';
                 }"/>
       
        <button type="submit" name="searchZip" value="searchZip" style="" class="btn btn-blue">find your store</button>
        </form>
     <!--  <small> &raquo; Enter US Zip Code OR Canadian Postal Code</small>-->
        </div>      
		<br>

		<?php //if(isset($view_canadian)){ echo $view_canadian; } ?>

			
        	<br />
            <?php Widget::render('find_us_sidebar_text');?>
        	<?php $form = getModel('form')->getForm(2);?>
<a href="<?php echo UPLOAD_URL.$form['form_file']?>" class="btn btn-blue">HDC Request Form</a>
        </div>

        </div>

        </td>
</tr>
<tr><td>&nbsp;</td></tr>
</table>
		<!---------------------------------------consuemer right end---------------------------------------------->

	</td>   
</tr>
</table>
</div>

</div>

<script type="text/javascript">
                                $(document).ready(function(){
                                    $('.scroll').tinyscrollbar();
                                });
                            </script>


