<?php loadHelper('url');?>
<?php $word_count = str_word_count($view_faq['faq_answer']);
$word_in_a_line = 12;

$lines = ceil($word_count/$word_in_a_line);
?>
<script type="text/javascript">
    $('.nav ul li.contact').attr('id','contact-active');
</script>
<div class="wrapper">
                <div class="faq">
                    <div class="faqLeft">
                        
                            
                                <div class="scroll">
                                <div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
                                <?php $height = ($lines - 1)* 30;?>
                                <?php if($height<440) $style="height:".($height+150)."px"; else $style='height:440px';?>
                                <div class="viewport" style="<?php echo $style?>">
                                <div class="overview" style="<?php echo $style?>">
                                <h1>Frequently asked questions</h1>
                                <h2><?php echo $view_faq['faq_question'];?></h2>
                                <p><?php echo $view_faq['faq_answer'];?></p>
                                <a href="<?php echo isset($_SERVER['HTTP_REFERER'])?$_SERVER['HTTP_REFERER']:URL.'faq'; ?>" class="faqback">&lt;back to FAQs</a>
                                </div>
                                </div>


                            <script type="text/javascript">
                                $(document).ready(function(){
                                    $(window).resize();
                                    $('.scroll').tinyscrollbar();
                                    $(window).resize();
                                    if($('.viewport').css('height') == '150px') $('.scrollbar').addClass('disable');
                                });
                            </script>
                        </div>
                    
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="faqRight">
                <a href="<?php echo URL.'contacts?from='.CurrentURL()?>" class="btn btn-blue">contact us regarding this issue</a>
            </div>
            <script>
             $(window).resize();
            </script>


   