
<!-- Name for inputs must be same as the database fields -->
<?php Session::showErrorMessages();?>
<?php Session::showSuccessMessages();?>
<?php loadHelper('inputs');?>
<div class="wrapper">
                <div class="contactPage">
                    <div class="contactForm">
                        <form method = "post" action = "<?php echo URL.'contacts/messagePost'?>">
                            <fieldset>
                                <label for ="sender_name"><b>name</b></label>
								<input type="text" class="input-box required text-validation" name="sender_name"/>
                            </fieldset>
                            <fieldset>
                               <label for = "sender_email"><b>email</b></label>
								<input type="text" class="input-box required email-validation" name="sender_email"/>
                            </fieldset>
                            <fieldset>
                                <label for ="message_nature"><b>nature of inquiry</b></label>
								<input type="text" class="input-box required text-validation" name="message_nature"/>
                            </fieldset>
                            <fieldset>
                               <label for ="message"><b>message</b></label>
								<textarea name="message" class="input-box required text-validation" rows="10" cols="60"></textarea>
								
                            </fieldset>
                            <fieldset class="align-right">
                            	<!-- <input type="submit" value = "Submit" class="submit-button"/> -->
                                <button class="btn btn-blue" onclick="$('.contactForm form').submit();">submit</button>
                            </fieldset>

                            <?php if(getParam('from')):?>
                                <fieldset>
                                    <label for ="from_url">Related To:</label>
                                    <input type="text" name="from_url" value="<?php echo getParam('from')?>" readonly/>
                                </fieldset>
                            <?php endif;?>
                        </form>
                    </div>
	                <!-- TODO MAKE THIS DYNAMIC -->
                    <div class="contactDetail">
                        <a href="<?php echo URL.'faq'?>" class="btn btn-blue btn-large">our FAQs</a>
                        <h1><?php echo getModel('configuration')->getConfigValue('company_name');?></h1>
                        <div class="middlepart">
                        <p><?php echo getModel('configuration')->getConfigValue('address_1');?></p>
                        <p><?php echo getModel('configuration')->getConfigValue('address_2');?>, <?php echo getModel('configuration')->getConfigValue('state');?> <?php echo getModel('configuration')->getConfigValue('zip');?></p>
                        </div>
                        <div class="bottompart">
                            <p><b class="normal">toll-free :</b> <?php echo getModel('configuration')->getConfigValue('toll_free');?></p>
                            <p style="margin-bottom:20px;"><b class="normal">fax :</b> <?php echo getModel('configuration')->getConfigValue('fax');?></p>
                            <p><b>Sales/Orders/Returns :</b><a href="mailto:<?php echo getModel('configuration')->getConfigValue('sales_email');?>" target="_top"><?php echo getModel('configuration')->getConfigValue('sales_email');?></a></p>
                            <p><b>Vendors :</b><a href="mailto:<?php echo getModel('configuration')->getConfigValue('vendor_email');?>" target="_top"><?php echo getModel('configuration')->getConfigValue('vendor_email');?></a></p>
                            <p><b>Marketing/Donations :</b> <a href="mailto:<?php echo getModel('configuration')->getConfigValue('marketing_email');?>" target="_top"><?php echo getModel('configuration')->getConfigValue('marketing_email');?></a></p>
                            <p><b>Employment/HR :</b> <a href="mailto:<?php echo getModel('configuration')->getConfigValue('employment_email');?>" target="_top"><?php echo getModel('configuration')->getConfigValue('employment_email');?></a></p>
                            <p><b>General Inquiries :</b> <a href="mailto:<?php echo getModel('configuration')->getConfigValue('general_email');?>" target="_top"><?php echo getModel('configuration')->getConfigValue('general_email');?></a></p>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>

<!-- <div class="contact-form">
	<form method = "post" action = "<?php echo URL.'contacts/messagePost'?>">
		<label for ="sender_name">Name:</label>
		<input type="text" class="input-box required text-validation" name="sender_name"/>
		<label for = "sender_email">Email:</label>
		<input type="text" class="input-box required email-validation" name="sender_email"/>
		<label for ="message_nature">Nature</label>
		<input type="text" class="input-box required number-validation" name="message_nature"/>
		<label for ="message">Nature</label>
		<textarea name="message" class="input-box required text-validation" rows="10" cols="60"></textarea>
		<input type="submit" value = "Submit" class="submit-button"/>
	</form>
</div> -->
<script>
$('.contactForm form').submit(function(){
	return $(this).validate('input-box');
});
</script>