<h1> Add Retailer Contact</h1>
<?php $session = Session::getCurrentSession();?>
<form method = "post" action = "<?php echo URL.'account/addRetailerContactPost'?>">
<input type="hidden" name="rid" value="<?php echo $session['user_id']?>"/>
<label for ="name">Post</label>
<input type="text" class="input-box required text-validation" name="mpost"/>
<label for ="name">Name</label>
<input type="text" class="input-box required text-validation" name="mname"/>
<label for ="name">Email</label>
<input type="text" class="input-box required email-validation" name="memail"/>
<!-- <label for ="name">Password</label>
<input type="password" class="input-box required text-validation" name="mpass"/>
 -->
<label for ="name">Address</label>
<input type="text" class="input-box required text-validation" name="madd"/>
<label for ="name">Apt/Ste</label>
<input type="text" class="input-box text-validation" name="madd2"/>
<label for ="name">City</label>
<input type="text" class="input-box required text-validation" name="mcity"/>
<label for ="name">State</label>
<input type="text" class="input-box required text-validation" name="mstate"/>
<label for ="name">Zip</label>
<input type="text" class="input-box required text-validation" name="mzip"/>
<label for ="name">Phone</label>
<input type="text" class="input-box required text-validation" name="mtel"/>
<label for ="name">Fax</label>
<input type="text" class="input-box required text-validation" name="mfax"/>
<!-- <label for ="name">Company/store</label>
<input type="text" class="input-box required text-validation" name="mcompany"/>
 --><!-- <label for ="name">Website</label>
<input type="text" class="input-box required text-validation" name="mein"/>
 -->
<!-- <label for ="name">EIN(tax ID)</label>
<input type="text" class="input-box required text-validation" name="mein"/>
 -->
<input type="hidden" value="customer" name="mtype"/>
<input type="submit" value="Submit"/>
</form>
