<?php //loadView('account/account-menu.phtml');?>
<?php $states = getModel('customer')->getAllStates();?>
<script type="text/javascript">

	$('.account-menu ul li a.cpanel').addClass('active');	

</script>
<div class="wrapper clearfix">
	<div class="add-store-form">
	<h1>Add/Manage Your Store(s)</h1>
		<form method="post" action="<?php echo (isset($view_store)?URL.'account/editStorePost':URL.'account/addStorePost')?>">
			<input type="hidden" name="rsid" value="<?php echo (isset($view_store)?$view_store['rsid']:null) ?>"/>
			<input type="hidden" name="rid" value="<?php echo $view_rid?>"/>
			<div class="half left-half">
			<fieldset>
			<label for = "rsnm">store name:</label>
			<input type="text" name="rsnm" class="input-box required text-validation" value="<?php echo (isset($view_store)?$view_store['rsnm']:null) ?>"/>
			</fieldset>
			<fieldset>
			<label for = "rsadd">address:</label>
			<input type="text" name="rsadd" class="input-box required text-validation" value="<?php echo (isset($view_store)?$view_store['rsadd']:null) ?>"/>
			</fieldset>
			<fieldset>
			<label for = "rscity">suite:</label>
			<input type="text" name="rsadd2" class="input-box text-validation" value="<?php echo (isset($view_store)?$view_store['rsadd2']:null) ?>"/>
			</fieldset>
			<fieldset>
			<label for = "rscity">city:</label>
			<input type="text" name="rscity" class="input-box required text-validation" value="<?php echo (isset($view_store)?$view_store['rscity']:null) ?>"/>
			</fieldset>
			<fieldset>
			<label for = "rsstate">state:</label>
			<select name="rsstate" class="input-box" style="width:360px;height: 46px;border: none;border-radius: 10px;">
						<?php foreach($states as $state):?>
							<option <?php echo (isset($view_store) and $view_store['rsstate'] == $state['abb'])?'selected':null?> value="<?php echo $state['abb']?>"><?php echo $state['stt_nm']?></option>
						<?php endforeach;?>
					</select>
			<!-- <input type="text" name="rsstate" class="input-box required text-validation" value="<?php echo (isset($view_store)?$view_store['rsstate']:null) ?>"/> -->
			</fieldset>
			<fieldset>
			<label for = "rszip">zip:</label>
			<input type="text" name="rszip" class="input-box required zip-validation" value="<?php echo (isset($view_store)?$view_store['rszip']:null) ?>"/>
			</fieldset>
			</div>
			<div class="half right-half">
			<fieldset>
			<label for = "rstel">Private No:</label>
			<input type="text" name="rstelprivate" class="input-box phone-validation" value="<?php echo (isset($view_store)?$view_store['rstelprivate']:null) ?>"/>
			</fieldset>
			<fieldset>
			<label for = "rstel">phone:</label>
			<input type="text" name="rstel" class="input-box required phone-validation" value="<?php echo (isset($view_store)?$view_store['rstel']:null) ?>"/>
			</fieldset>
			<fieldset>
			<label for = "rsfax">fax:</label>
			<input type="text" name="rsfax" class="input-box fax-validation" value="<?php echo (isset($view_store)?$view_store['rsfax']:null) ?>"/>
			</fieldset>
			<fieldset>
			<label for = "rsemail">Private email:</label>
			<input type="text" name="rsemailprivate" class="input-box email-validation" value="<?php echo (isset($view_store)?$view_store['rsemailprivate']:null) ?>"/>
			</fieldset>
			<fieldset>
			<label for = "rsemail">email:</label>
			<input type="text" name="rsemail" class="input-box required email-validation" value="<?php echo (isset($view_store)?$view_store['rsemail']:null) ?>"/>
			</fieldset>
			<fieldset>
			<label for = "rswebsite">website:</label>
			<input type="text" name="rswebsite" class="input-box text-validation" value="<?php echo (isset($view_store)?$view_store['rswebsite']:null) ?>"/>
			</fieldset>
			<fieldset>
		<input type="checkbox" class="input-box required css-checkbox" checkboxname="privacy-policy" id="checkboxG1"/><label for="checkboxG1" class="css-label radGroup1">I have read the <a href="<?php echo URL.'pages/privacypolicy'?>">Privacy Policy</a> and <a href="<?php echo URL.'pages/webusage'?>">Web Usage Agreement</a></label>
		</fieldset>
		<fieldset>
			<label></label>
			<input type="submit" value="submit" class="btn btn-blue left-btn" />
			<input type="button" value="clear" class="btn btn-blue right-btn" onclick="clearForm();" />
		</fieldset>
	</div>
	
		</form>
	</div>
</div>
<script>
$(document).ready(function(){
	$('.add-store-form form').submit(function(){
		return $(this).validate('input-box');
	});
});
function clearForm()
	{
		$('.add-store-form form').find('input[type=text]').val('');
		$('.left-btn').val('submit');
		$('.right-btn').val('clear');
	}
</script>