<?php echo Session::showErrorMessages();
echo Session::showSuccessMessages();?>
<?php $session = Session::getCurrentSession();
$customer = getModel('customer')->getCustomer($session['user_id']);
extract($customer);
?>
<div class="edit-retailer-form">
<form method = "post" action = "<?php echo URL.'account/editPost'?>">
<input type="hidden" value="<?php echo $mid?>" name="mid"/>
<label for ="name">Name</label>
<input type="text" class="input-box required text-validation" name="mname" value="<?php echo $mname?>"/>
<label for ="name">Email</label>
<input type="text" class="input-box required email-validation" name="memail" value="<?php echo $memail?>"/>
<label for ="name">Address</label>
<input type="text" class="input-box required text-validation" name="madd" value="<?php echo $madd?>"/>
<label for ="name">Apt/Ste</label>
<input type="text" class="input-box text-validation" name="madd2" value="<?php echo $madd2?>"/>
<label for ="name">City</label>
<input type="text" class="input-box required text-validation" name="mcity" value="<?php echo $mcity?>"/>
<label for ="name">State</label>
<input type="text" class="input-box required text-validation" name="mstate" value="<?php echo $mstate?>"/>
<label for ="name">Zip</label>
<input type="text" class="input-box required text-validation" name="mzip" value="<?php echo $mzip?>"/>
<label for ="name">Phone</label>
<input type="text" class="input-box required text-validation" name="mtel" value="<?php echo $mtel?>"/>
<label for ="name">Fax</label>
<input type="text" class="input-box required text-validation" name="mfax" value="<?php echo $mfax?>"/>
<label for ="name">Company/store</label>
<input type="text" class="input-box required text-validation" name="mcompany" value="<?php echo $mcompany?>"/>
<!-- <label for ="name">Website</label>
<input type="text" class="input-box required text-validation" name="mein"/>
 -->
<input type="submit" value="Submit"/>

	</form>

</div>


<div class="password-form">
<form method="post" action ="<?php echo URL.'account/editPassword'?>">
<input type="hidden" value="<?php echo $mid?>" name="mid"/>
<label for = "oldpassword">Old Password</label>
<input type="password" name="oldpassword" class="input-box required equal"/>
<label for = "newpassword">New Password</label>
<input type="password" name="newpassword" class="input-box required password"/>
<label for = "newpassword1">New Password Again</label>
<input type="password" name="newpassword1" class="input-box required confirm-password"/>
<input type="submit" value="Save"/>
</form>
</div>
<script>
$(document).ready(function(){
	$('.edit-retailer-form form').submit(function(){
	return $(this).validate('input-box');
});
$('.password-form form').submit(function(){
	return $(this).validate('input-box');
});

})
</script>