<a href="<?php echo URL.'account/addRetailerContact'?>">Add New Contact</a>
<?php if(isset($view_contacts)):?>
	<ul>
	<?php foreach($view_contacts as $contact):?>
		<li>
			<p><?php echo $contact['retailer_designation'];?></p>
			<p><?php echo $contact['mname'];?></p>
			<p><?php echo $contact['memail'];?></p>
			<p><?php echo $contact['madd'];?></p>
			<p><?php echo $contact['mcity'];?></p>
			<p><?php echo $contact['mstate'];?></p>
			<p><?php echo $contact['mzip'];?></p>
			<p><?php echo $contact['mtel'];?></p>
			<p><?php echo $contact['mfax'];?></p>
		</li>
	<?php endforeach;?>
	</ul>
<?php endif;?>