<?php echo Session::showErrorMessages();
echo Session::showSuccessMessages();?>

<script type="text/javascript">
	$('.account-menu ul li a.cpanel').addClass('active');	
</script>

<div class="wrapper retailercontacts clearfix">
<a href="<?php echo URL.'account/addRetailerContact'?>" class="btn btn-blue" >Add New Contact</a>
<div class="left-half">
<?php if(isset($view_contacts)):?>
	<div class="scroll">
    <div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
    <div class="viewport" style="height:340px">
    <div class="overview" style="height:315px">
	<ul class="contacts">
	<?php foreach($view_contacts as $contact):?>
		<li>
		<div class="title">
			<p><span class="name"><?php echo $contact['mname'];?></span> &gt;&gt; <span class="phone"><?php echo $contact['mtel'];?></span></p> 
		</div>
			<div class="store-action">
						<ul>
							<li><a href="<?php echo URL.'account/editRetailerContact/'.$contact['retailer_contact_id']?>" >edit</a></li>
							<li>|</li>
							<li><a href="<?php echo URL.'account/deleteContactAction/'.$contact['retailer_contact_id']?>" >delete</a></li>
						</ul>
					</div>
		<div class="info">
			<p><?php echo $contact['retailer_designation'];?></p>
			<p><?php echo $contact['madd'];?>, <?php echo $contact['mcity'];?>, <?php echo $contact['mstate'];?> <?php echo $contact['mzip'];?></p>
			<p><?php echo $contact['memail'];?></p>
			<p><?php echo $contact['mfax'];?></p>
		</div>
			
		</li>
	<?php endforeach;?>
	</ul>
	</div>
	<script>
	 $(document).ready(function(){
            $(window).resize();
            $('.scroll').tinyscrollbar();
             $(window).resize();
        });
	</script>
<?php endif;?>
</div>
</div>
</div>
<div class="right-half clearfix">
<div class="right-content">
<p style="font-size:13px"><strong style="font-family:MyriadProBold; font-size:16px"> Can’t find the store you’re looking for? </strong><br>Click the button below if your contact(s) does <br>not show in the box to the left. </p>
<a href="<?php echo URL.'contacts'?>" class="btn btn-blue contacts">contact us regarding this issue</a>
</div>
</div>
</div>