<?php loadHelper('view');?>
<style>
#cropContainerHeader {
			width: 200px;
			height: 150px;
			position:relative; /* or fixed or absolute */
		}
		#cropContainerModal0, #cropContainerModal1, .croppic { width:200px; height:200px; position: relative; border:1px solid #ccc;}

</style>
<?php if(!isset($view_product)):?>

<div class="product-form">
	<form method="post" enctype="multipart/form-data" action="<?php echo ADMIN_URL.'products/addPost'?>">
		<input type="hidden" name="attribute_set" value="<?php echo $view_set?>"/>
		<input type="hidden" name="product_type" value="<?php echo $view_type?>"/>
		<label for = "name">Name</label>
		<input type="text" class="input-box required text-validation" name="name"/>
		<label for = "name">Sku</label>
		<input type="text" class="input-box required text-validation" name="sku"/>
		<label for = "quantity">Quantity Available</label>
		<input type="text" class="input-box required text-validation" name="quantity"/>
		<label for = "in_stock">Product in Stock</label>
		<select name="in_stock">
			<option value="0"><?php echo convertStockIdToText(0);?></option>
			<option value="1"><?php echo convertStockIdToText(1);?></option>
		</select>
		<label for = "status">Product Status</label>
		<select name="status">
			<option value="0"><?php echo convertStatusIdToText(0);?></option>
			<option value="1"><?php echo convertStatusIdToText(1);?></option>
		</select>

		<?php if(isset($view_attributes)):?>
			<?php foreach ($view_attributes as $attribute):?>
				<label for = <?php echo $attribute['acode']?>><?php echo $attribute['aname']?></label>
				<?php switch($attribute['atype']): 
				case 'int':?>
					<input type=<?php echo $attribute['atype']?> name="attributes[<?php echo $attribute['acode']?>]"/>
				<?php break;?>
				<?php case 'varchar':?>
					<input type=<?php echo $attribute['atype']?> name="attributes[<?php echo $attribute['acode']?>]"/>
				<?php break;?>
				<?php case 'text':?>
					<textarea class="editor" name="attributes[<?php echo $attribute['acode']?>]"></textarea>
				<?php break;?>
				<?php case 'select':?>
					<select name="attributes[<?php echo $attribute['acode']?>]">
						<?php $options = getModel('attribute')->getAttributeOptions($attribute['aid'])?>
						<?php foreach($options as $option):?>
							<option value=<?php echo $option['vid']?>><?php echo $option['value']?></option>
						<?php endforeach;?>
					</select>
				<?php break;?>
				<?php endswitch;?>
			<?php endforeach;?>
		<?php endif;?>

		</br></br>
		<?php if(isset($view_catlist)){ $i=1;?>
		<label for ="category">Category </label>
		</br>
		<?php foreach ($view_catlist as $view_catlist) { ?>	
		<input type="checkbox" id="pc<?php echo $i; ?>" name="pccheck_list[<?php echo $i; ?>]" value="<?php echo $view_catlist['category_id']; ?>" />
		<label for="pc<?php echo $i; ?>"><span></span><?php echo $view_catlist['category_name']; ?></label></br>
		<?php $i++;}?>
		<?php } ?>


<!-- 		<a href="javascript:void(0)" class="add-image">Add Image</a>
		<table>
			<thead>
				<th>Image</th>
			</thead>
			<?php $base_count = 0; $thumb_count =0; ?>
			<tbody class="gallery-table">
				<tr>
					<td><input type="file" name="gallery[]"/></td>
				</tr>
			</tbody>
		</table>
 -->

<a href="javascript:void(0)" class="add" id='0'>Add Another Image</a>
<div class="images">
<div class="croppic" id="cropContainerModal-0"></div>
<input type="hidden" name="gallery_images[]" id='input-0'/>
</div>
<script>

var croppicContainerModalOptions = {
				uploadUrl:'<?php echo ADMIN_URL?>products/uploadImage',
				cropUrl:'<?php echo ADMIN_URL?>products/cropImage',
				modal:true,
				imgEyecandyOpacity:0.4,
				loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',
				onAfterImgCrop:		function(){var classs = $(this).attr('id'); var id = classs.split('-')[1];$('#input-'+id).val(response.file);}
		}

		var cropContainerModal = new Croppic('cropContainerModal-0', croppicContainerModalOptions);

		$('a.add').click(function(){
			var id = parseInt($(this).attr('id')) + 1;
			croppicContainerModalOptions.outputUrlId = 'outputUrlId'+id;
			$('.images').append('<div id="cropContainerModal-'+id+'" class="croppic"></div><input type="hidden" name="gallery_images[]" id="input-'+id+'"/></div>');

			var script   = document.createElement("script");
				script.type  = "text/javascript";
				script.text  = "var cropContainerModal = new Croppic('cropContainerModal-"+id+"', croppicContainerModalOptions);";               // use this for inline script
				document.body.appendChild(script);
			$(this).attr('id',id);
		});
</script>
		<input type="submit" value="Save"/>


	</form>


	<!-- <form  method="post" action="<?php echo ADMIN_URL.'products/test'?>">
		<input type="file" name="file[]"  >
		<input type="file" name="file[]" >
		<input type="file" name="file[]" >

			<input type="submit" value="Save"/>
	</form> -->

	<script>
		$(document).ready(function()
		{
			//$("#default-base").attr('checked','checked');
			//$("#default-thumbnail").attr('checked','checked');
			$('a.add-image').click(function(){
				$('tbody.gallery-table').append('<tr class="option"><td><input type="file" name="gallery[]"/></td><td><a href="javascript:void(0)" class="remove-image">Remove Image</a></td></tr>');
				var script   = document.createElement("script");
				script.type  = "text/javascript";
				script.text  = "$('a.remove-image').click(function(){$(this).parent().parent().remove()});";               // use this for inline script
				document.body.appendChild(script);
			});

			
		});
	</script>
</div>

<?php else:?>
	<div class="product-form">
	<form method="post" enctype="multipart/form-data" action="<?php echo ADMIN_URL.'products/editPost'?>">
		<input type="hidden" name="product_id" value="<?php echo $view_product['pid']?>"/>
		<input type="hidden" name="attribute_set" value="<?php echo $view_product['product_asid']?>"/>
		<input type="hidden" name="product_type" value="<?php echo $view_product['ptype']?>"/>
		<label for = "name">Name</label>
		<input type="text" class="input-box required text-validation" name="name" value="<?php echo $view_product['pname']?>"/>
		<label for = "name">Sku</label>
		<input type="text" class="input-box required text-validation" name="sku" value="<?php echo $view_product['psku']?>"/>
		<label for = "quantity">Quantity Available</label>
		<input type="text" class="input-box required text-validation" name="quantity" value="<?php echo $view_product['quantity']?>"/>
		<label for = "in_stock">Product in Stock</label>
		<select name="in_stock">
			<option value="0" <?php echo ($view_product['in_stock'] == 0)?'selected':null?>><?php echo convertStockIdToText(0);?></option>
			<option value="1" <?php echo ($view_product['in_stock'] == 1)?'selected':null?>><?php echo convertStockIdToText(1);?></option>
		</select>
		<label for = "status">Product Status</label>
		<select name="status">
			<option value="0" <?php echo ($view_product['status'] == 0)?'selected':null?>><?php echo convertStatusIdToText(0);?></option>
			<option value="1" <?php echo ($view_product['status'] == 1)?'selected':null?>><?php echo convertStatusIdToText(1);?></option>
		</select>

		<?php if(isset($view_attributes)):?>
			<?php foreach ($view_attributes as $attribute):?>
				<label for = <?php echo $attribute['acode']?>><?php echo $attribute['aname']?></label>
				<?php switch($attribute['atype']): 
				case 'int':?>
					<input type=<?php echo $attribute['atype']?> name="attributes[<?php echo $attribute['acode']?>]" value="<?php echo getModel('products')->getProductAttributeById($view_product['pid'], $attribute['aid'])?>"/>
				<?php break;?>
				<?php case 'varchar':?>
					<input type=<?php echo $attribute['atype']?> name="attributes[<?php echo $attribute['acode']?>]" value="<?php echo getModel('products')->getProductAttributeById($view_product['pid'], $attribute['aid'])?>"/>
				<?php break;?>
				<?php case 'text':?>
					<textarea class = "editor" name="attributes[<?php echo $attribute['acode']?>]"><?php echo getModel('products')->getProductAttributeById($view_product['pid'], $attribute['aid'])?></textarea>
				<?php break;?>
				<?php case 'select':?>
					<select name="attributes[<?php echo $attribute['acode']?>]">
						<?php $options = getModel('attribute')->getAttributeOptions($attribute['aid'])?>
						<?php foreach($options as $option):?>
							<option value=<?php echo $option['vid']?>  <?php echo (getModel('products')->getProductAttributeById($view_product['pid'], $attribute['aid']) == $option['vid'])?'selected':null?>><?php echo $option['value']?></option>
						<?php endforeach;?>
					</select>
				<?php break;?>
				<?php endswitch;?>
			<?php endforeach;?>
		<?php endif;?>

		</br></br>
		<?php if(isset($view_catlist)){ $i=1;?>
		<label for ="category">Category </label>
		</br>
		<?php foreach ($view_catlist as $view_catlist) { ?>	
		<input type="checkbox" id="pc<?php echo $i; ?>" name="pccheck_list[<?php echo $i; ?>]" value="<?php echo $view_catlist['category_id']; ?>" 
		<?php if(is_array($view_CatInList) and in_array($view_catlist['category_id'], $view_CatInList)) { echo'checked'; }?> />
		<label for="pc<?php echo $i; ?>"><span></span><?php echo $view_catlist['category_name']; ?></label></br>
		<?php $i++;}?>
		<?php } ?>

<!-- <a href="javascript:void(0)" class="add-image">Add Image</a> -->
			<table>
			<thead>
			<th>Image</th>
			<!-- <th>Base Image</th>
			<th>Thumbnail</th> -->
			</thead>
			<tbody class="gallery-table">
		<?php if(isset($view_gallery)):?>
			<?php foreach($view_gallery as $image):?>
				<tr>
					<td><img src="<?php echo UPLOAD_URL.$image['value']?>" width="100" height="100"/></td>
					<!-- <td><input type="radio" name="base_image" <?php echo ($image['is_base_image'])?'class="checked"':null?>/></td>
					<td><input type="radio" name="thumbnail" <?php echo ($image['is_thumbnail_image'])?'class="checked"':null?>/></td> -->
					<td><a href="javascript:void(0)" class="remove-uploaded-image" rel="<?php echo $image['gid']?>">Remove Image</a>
				</tr>
			<?php endforeach;?>
		<?php endif;?>
			<?php $base_count = 0; $thumb_count =0; ?>
<!-- 				<tr class="option">
					<td><input type="file" name="gallery[]"/></td>
					<td><input type="radio" name="base_image" id="default-base" value="<?php echo $base_count++?>" /></td>
					<td><input type="radio" value="<?php echo $thumbnail?>" id ="default-thumbnail" name="thumbnail"/></td>
					<td><a href="javascript:void(0)" class="remove-image-default">Remove Image</a></td>
				</tr>
 -->			</tbody>
		</table>


		<a href="javascript:void(0)" class="add" id='0'>Add Another Image</a>
<div class="images">
<!-- <div class="croppic" id="cropContainerModal-0"></div>
 <input type="hidden" name="gallery_images[]" id='input-0'/>
-->
</div>
<script>

var croppicContainerModalOptions = {
				uploadUrl:'<?php echo ADMIN_URL?>products/uploadImage',
				cropUrl:'<?php echo ADMIN_URL?>products/cropImage',
				modal:true,
				imgEyecandyOpacity:0.4,
				loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',
				onAfterImgCrop:		function(){var classs = $(this).attr('id'); var id = classs.split('-')[1];$('#input-'+id).val(response.file);}
		}

		//var cropContainerModal = new Croppic('cropContainerModal-0', croppicContainerModalOptions);

		$('a.add').click(function(){
			var id = parseInt($(this).attr('id')) + 1;
			croppicContainerModalOptions.outputUrlId = 'outputUrlId'+id;
			$('.images').append('<div id="cropContainerModal-'+id+'" class="croppic"></div><input type="hidden" name="gallery_images[]" id="input-'+id+'"/></div>');

			var script   = document.createElement("script");
				script.type  = "text/javascript";
				script.text  = "var cropContainerModal = new Croppic('cropContainerModal-"+id+"', croppicContainerModalOptions);";               // use this for inline script
				document.body.appendChild(script);
			$(this).attr('id',id);
		});
</script>
		<input type="submit" value="Save"/>


	</form>
	<script>
		$(document).ready(function()
		{

			$('.remove-uploaded-image').click(function(){
				var answer = confirm('Are you sure you want to delete this image?');
				$image = $(this);
				if(answer)
				{
					var gid = $(this).attr('rel');

					$.ajax({url:"<?php echo ADMIN_URL?>"+"products/deleteImage/"+gid,success:function(result){
						if(result == 'success')
						{
							$image.parent().parent().remove();
							alert('Image has been Deleted');
						}
						else
						{
							alert("Image Could Not Be Deleted");
						}
					  }});
				}
				else
				{
					return false;
				}
			});



			//$('.checked').attr('checked','checked');
			$('a.remove-image-default').click(function(){
				$(this).parent().parent().remove();
			})
			// $('a.add-image').click(function(){
			// 	$('tbody.gallery-table').append('<tr class="option"><td><input type="file" name="gallery[]"/></td><td><a href="javascript:void(0)" class="remove-image">Remove Image</a></td></tr>');
			// 	var script   = document.createElement("script");
			// 	script.type  = "text/javascript";
			// 	script.text  = "$('a.remove-image').click(function(){$(this).parent().parent().remove()});";               // use this for inline script
			// 	document.body.appendChild(script);
			// });

			
		});
	</script>
</div>
<?php endif;?>
	<script>
$('form').submit(function(){
	return $(this).validate('input-box');
});
</script>