<?php loadHelper('view');?>
<?php if(!isset($view_product)):?>
<div class="product-form">
	<form method="post" action="<?php echo ADMIN_URL.'products/addPost'?>">
		<input type="hidden" name="attribute_set" value="<?php echo $view_set?>"/>
		<input type="hidden" name="product_type" value="<?php echo $view_type?>"/>
		<label for = "name">Name</label>
		<input type="text" class="input-box required text-validation" name="name"/>
		<label for = "name">Sku</label>
		<input type="text" class="input-box required text-validation" name="sku"/>
		<label for = "quantity">Quantity Available</label>
		<input type="text" class="input-box required text-validation" name="quantity"/>
		<label for = "in_stock">Product in Stock</label>
		<select name="in_stock">
			<option value="0"><?php echo convertStockIdToText(0);?></option>
			<option value="1"><?php echo convertStockIdToText(1);?></option>
		</select>
		<label for = "status">Product Status</label>
		<select name="status">
			<option value="0"><?php echo convertStatusIdToText(0);?></option>
			<option value="1"><?php echo convertStatusIdToText(1);?></option>
		</select>

		<?php if(isset($view_attributes)):?>
			<?php foreach ($view_attributes as $attribute):?>
				<label for = <?php echo $attribute['acode']?>><?php echo $attribute['aname']?></label>
				<?php switch($attribute['atype']): 
				case 'int':?>
					<input type=<?php echo $attribute['atype']?> name="attributes[<?php echo $attribute['acode']?>]"/>
				<?php break;?>
				<?php case 'varchar':?>
					<input type=<?php echo $attribute['atype']?> name="attributes[<?php echo $attribute['acode']?>]"/>
				<?php break;?>
				<?php case 'text':?>
					<textarea name="attributes[<?php echo $attribute['acode']?>]"></textarea>
				<?php break;?>
				<?php case 'select':?>
					<select name="attributes[<?php echo $attribute['acode']?>]">
						<?php $options = getModel('attribute')->getAttributeOptions($attribute['aid'])?>
						<?php foreach($options as $option):?>
							<option value=<?php echo $option['vid']?>><?php echo $option['value']?></option>
						<?php endforeach;?>
					</select>
				<?php break;?>
				<?php endswitch;?>
			<?php endforeach;?>
		<?php endif;?>

		<input type="submit" value="Save"/>


	</form>

	<form enctype="multipart/form-data" method="post" action="<?php echo ADMIN_URL.'products/test'?>">
		<input type="file" name="file[]"  >
		<input type="file" name="file[]" >
		<input type="file" name="file[]" >

			<input type="submit" value="Save"/>
	</form>
</div>

<?php else:?>
	<div class="product-form">
	<form method="post" action="<?php echo ADMIN_URL.'products/editPost'?>">
		<input type="hidden" name="product_id" value="<?php echo $view_product['pid']?>"/>
		<input type="hidden" name="attribute_set" value="<?php echo $view_product['product_asid']?>"/>
		<input type="hidden" name="product_type" value="<?php echo $view_product['ptype']?>"/>
		<label for = "name">Name</label>
		<input type="text" class="input-box required text-validation" name="name" value="<?php echo $view_product['pname']?>"/>
		<label for = "name">Sku</label>
		<input type="text" class="input-box required text-validation" name="sku" value="<?php echo $view_product['psku']?>"/>
		<label for = "quantity">Quantity Available</label>
		<input type="text" class="input-box required text-validation" name="quantity" value="<?php echo $view_product['quantity']?>"/>
		<label for = "in_stock">Product in Stock</label>
		<select name="in_stock">
			<option value="0" <?php echo ($view_product['in_stock'] == 0)?'selected':null?>><?php echo convertStockIdToText(0);?></option>
			<option value="1" <?php echo ($view_product['in_stock'] == 1)?'selected':null?>><?php echo convertStockIdToText(1);?></option>
		</select>
		<label for = "status">Product Status</label>
		<select name="status">
			<option value="0" <?php echo ($view_product['status'] == 0)?'selected':null?>><?php echo convertStatusIdToText(0);?></option>
			<option value="1" <?php echo ($view_product['status'] == 1)?'selected':null?>><?php echo convertStatusIdToText(1);?></option>
		</select>

		<?php if(isset($view_attributes)):?>
			<?php foreach ($view_attributes as $attribute):?>
				<label for = <?php echo $attribute['acode']?>><?php echo $attribute['aname']?></label>
				<?php switch($attribute['atype']): 
				case 'int':?>
					<input type=<?php echo $attribute['atype']?> name="attributes[<?php echo $attribute['acode']?>]" value="<?php echo getModel('products')->getProductAttributeById($view_product['pid'], $attribute['aid'])?>"/>
				<?php break;?>
				<?php case 'varchar':?>
					<input type=<?php echo $attribute['atype']?> name="attributes[<?php echo $attribute['acode']?>]" value="<?php echo getModel('products')->getProductAttributeById($view_product['pid'], $attribute['aid'])?>"/>
				<?php break;?>
				<?php case 'text':?>
					<textarea name="attributes[<?php echo $attribute['acode']?>]"><?php echo getModel('products')->getProductAttributeById($view_product['pid'], $attribute['aid'])?></textarea>
				<?php break;?>
				<?php case 'select':?>
					<select name="attributes[<?php echo $attribute['acode']?>]">
						<?php $options = getModel('attribute')->getAttributeOptions($attribute['aid'])?>
						<?php foreach($options as $option):?>
							<option value=<?php echo $option['vid']?>  <?php echo (getModel('products')->getProductAttributeById($view_product['pid'], $attribute['aid']) == $option['vid'])?'selected':null?>><?php echo $option['value']?></option>
						<?php endforeach;?>
					</select>
				<?php break;?>
				<?php endswitch;?>
			<?php endforeach;?>
		<?php endif;?>

		<input type="submit" value="Save"/>


	</form>
</div>
<?php endif;?>