<?php loadHelper('view');?>
<?php loadHelper('inputs');?>
<style>

#cropContainerHeader {
			width: 500px;
			height: 350px;
			position:relative; /* or fixed or absolute */
		}
		#cropContainerModal0, #cropContainerModal1, .croppic { width:500px; height:350px; position: relative; border:1px solid #ccc;}

</style>
<form method="post" enctype="multipart/form-data" action="<?php echo ADMIN_URL.'products/addVariation'?>">
		<input type="hidden" name="attribute_set" value="<?php echo $view_set?>"/>
		<input type="hidden" name="product_type" value="1"/>
		<input type="hidden" name="is_variation" value="1"/>
		<label for = "name">Name</label>
		<input type="text" class="input-box required text-validation" name="name"/>
		<label for = "name">Sku</label>
		<input type="text" class="input-box required text-validation" name="sku"/>
		<label for = "quantity">Quantity Available</label>
		<input type="text" class="input-box required text-validation" name="quantity"/>
		<label for = "in_stock">Product in Stock</label>
		<select name="in_stock">
			<option value="0"><?php echo convertStockIdToText(0);?></option>
			<option value="1"><?php echo convertStockIdToText(1);?></option>
		</select>
		<label for = "status">Product Status</label>
		<select name="status">
			<option value="0"><?php echo convertStatusIdToText(0);?></option>
			<option value="1"><?php echo convertStatusIdToText(1);?></option>
		</select>

		<?php if(isset($view_attributes)):?>
			<?php foreach ($view_attributes as $attribute):?>
				<label for = <?php echo $attribute['acode']?>><?php echo $attribute['aname']?></label>
				<?php switch($attribute['atype']): 
				case 'int':?>
					<input type=<?php echo $attribute['atype']?> name="attributes[<?php echo $attribute['acode']?>]"/>
				<?php break;?>
				<?php case 'varchar':?>
					<input type=<?php echo $attribute['atype']?> name="attributes[<?php echo $attribute['acode']?>]"/>
				<?php break;?>
				<?php case 'text':?>
					<textarea class="editor" name="attributes[<?php echo $attribute['acode']?>]" style="width: 400px"></textarea>
				<?php break;?>
				<?php case 'select':?>
					<select name="attributes[<?php echo $attribute['acode']?>]">
						<?php $options = getModel('attribute')->getAttributeOptions($attribute['aid'])?>
						<?php foreach($options as $option):?>
							<option value=<?php echo $option['vid']?>><?php echo $option['value']?></option>
						<?php endforeach;?>
					</select>
				<?php break;?>
				<?php endswitch;?>
			<?php endforeach;?>
		<?php endif;?>

<a href="javascript:void(0)" class="add" id='0'>Add Another Image</a>
<div class="images">
<div class="croppic" id="cropContainerModal-0"></div>
<input type="hidden" name="gallery_images[]" id='input-0'/>
</div>
<script>

var croppicContainerModalOptions = {
				uploadUrl:'<?php echo ADMIN_URL?>products/uploadImage',
				cropUrl:'<?php echo ADMIN_URL?>products/cropImage',
				modal:true,
				imgEyecandyOpacity:0.4,
				loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',
				onAfterImgCrop:		function(){var classs = $(this).attr('id'); var id = classs.split('-')[1];$('#input-'+id).val(response.file);}
		}

		var cropContainerModal = new Croppic('cropContainerModal-0', croppicContainerModalOptions);

		$('a.add').click(function(){
			var id = parseInt($(this).attr('id')) + 1;
			croppicContainerModalOptions.outputUrlId = 'outputUrlId'+id;
			$('.images').append('<div id="cropContainerModal-'+id+'" class="croppic"></div><input type="hidden" name="gallery_images[]" id="input-'+id+'"/></div>');

			var script   = document.createElement("script");
				script.type  = "text/javascript";
				script.text  = "var cropContainerModal = new Croppic('cropContainerModal-"+id+"', croppicContainerModalOptions);";               // use this for inline script
				document.body.appendChild(script);
			$(this).attr('id',id);
		});
</script>
<script>
		$(document).ready(function()
		{
			$('a.add-image').click(function(){
				$('tbody.gallery-table').append('<tr class="option"><td><input type="file" name="gallery[]"/></td><td><a href="javascript:void(0)" class="remove-image">Remove Image</a></td></tr>');
				var script   = document.createElement("script");
				script.type  = "text/javascript";
				script.text  = "$('a.remove-image').click(function(){$(this).parent().parent().remove()});";               // use this for inline script
				document.body.appendChild(script);
			});

			
		});
	</script>
 
		</script>
		<input type="submit" value="save"/>
</form>
