<div class="wrapper creation">
<div class="rightBody"><img src="<?php echo ASSET_URL.'/images/creation-main.png'?>"></div>
<div class="leftBody">
<ul class="category-list">
<?php foreach($view_categories as $category):?>
	<?php if(!$category['is_root']):?>
		<li><a href="<?php echo URL.'products/list/'.$category['category_id']?>"><?php echo $category['category_name']?></a></li>
	<?php endif;?>
<?php endforeach;?>
</ul>
</div>
</div>
