<!-- FOR CATEGORY DOG CHEWS -->
<?php loadHelper('flickr_image');?>
<script type="text/javascript">
	$('.nav ul li.creation').attr('id','creation-active');
</script>
<?php $for_dogs_under = getModel('configuration')->getConfigValue('for_dogs_under');?>
<?php $for_all_dog_sizes = getModel('configuration')->getConfigValue('for_all_dog_sizes');?>
<?php $back_to_creations = getModel('configuration')->getConfigValue('back_to_creation');?>
<?php $end_pieces = getModel('configuration')->getConfigValue('what_to_do_with_end_pieces');?>
<?php $microwaving_tutorial = getModel('configuration')->getConfigValue('microwaving_tutorial');?>
<?php if(count($view_products)>0):?>
<?php if($view_category['cat_slug'] != 'yaky-sticks'):?>
	<div class="wrapper creationDetail">
		<div class="dog-chews">
			<div class="leftBody">
				<div class="description">
					<?php if(isset($view_category)):?>
						<h1><?php echo $view_category['category_name']?></h1>
						<div class="category-description-new">
							<?php echo $view_category['category_description'];?>
						</div>
					<?php endif;?>

				</div>
				<div class="actions">
				<?php if($view_category['cat_slug'] == 'dog-chews' or $view_category['cat_slug'] == 'chews-red' or $view_category['cat_slug'] == 'chews-green' or $view_category['cat_slug'] == 'chews-blue' or $view_category['cat_slug'] == 'chews-yellow' or $view_category['cat_slug'] == 'chews-gray'):?>
						<a href="<?php echo URL.'pages/endpieces'?>" class="btn btn-blue" style="padding:15px 0px; margin-top:-2px"><?php echo $end_pieces?></a>
				<?php elseif($view_category['cat_slug'] == 'yaky-nugget'):?>
						<a href="<?php echo URL.'pages/microwave'?>" class="btn btn-blue"><?php echo $microwaving_tutorial?></a>
				<?php endif;?>
				<?php $session = Session::getCurrentSession();?>
				<?php if($session):?>
				<?php $retailer = getModel('customer')->getRetailer($session['user_id']);?>
				<?php if($retailer):?>
					<!-- <a href="<?php echo URL.'account'?>" class="btn btn-blue retailer-menu">&lt; back to retailer menu</a> -->
				<?php endif;?>
			<?php endif;?>
				</div>
			</div>

			<?php if(isset($view_products)):?>
				<div class="rightBody">
					<div class="product-list-header">
					<?php if($view_category['cat_slug'] != 'ruff_roots'):?>
					<?php $dog_size = getModel('products')->getProductAttributeByCode($view_products[0]['pid'], 'dog_size');
					if($view_category['cat_slug'] == 'dog-chews' or $view_category['cat_slug'] == 'chews-red' or $view_category['cat_slug'] == 'chews-green' or $view_category['cat_slug'] == 'chews-blue' or $view_category['cat_slug'] == 'chews-yellow' or $view_category['cat_slug'] == 'chews-gray'):?>
						<span class="left dogchews-left" ><?php echo $for_dogs_under?> <span class="dog-size"><?php echo $dog_size?></span></span>
					<?php else:?>
						<span class="left" ><?php echo $for_all_dog_sizes?></span>
					<?php endif;?>
				<?php endif;?>
					<span class="right"><a href="<?php echo URL.'products/categories'?>"><?php echo $back_to_creations?></a></span>
					</div>
					<?php if(count($view_products) > 1):?>
						<div class="categoryContainer <?php echo (strtolower($view_category['cat_slug']) == 'yaky-yams')?'yakyyam':null?><?php echo (strtolower($view_category['cat_slug']) == 'ruff_roots')?'ruff_roots':null?>">
							<div class="product-list">
								<ul class="list">
								<?php $display_name_array = array()?>
								<?php $product_sku_array = array()?>
								<?php $product_id_array = array();?>
									<?php foreach($view_products as $product):?>
										<?php $product_id = $product['pid'];?>
										<?php $productModel = getModel('products');?>
										<?php $displayName =  $productModel->getProductAttributeByCode($product_id,'display_name');?>
										<?php if($displayName == false) $displayName = $product['pname'];?>
										<?php
										$class = null;
										array_push($display_name_array, $displayName);
										array_push($product_sku_array, $product['psku']);
										array_push($product_id_array, $product['pid']);
										?>
									<?php endforeach;?>
									<?php if($view_category['cat_slug'] != 'yaky-yams'):?>
										<?php //sort($display_name_array, SORT_STRING);?>
										<?php $count = 0;?>
										<?php foreach ($display_name_array as $displayName):?>
											<?php
												//echo $displayName;
												if($displayName == '15 lbs') $class = 'blue';
												if($displayName == '70 lbs') $class="grey";
												if($displayName == '35 lbs') $class = "green";
												if($displayName == '55 lbs') $class = "red";
												if($displayName == '65 lbs') $class = "yellow";
												if($displayName == 'seedling') $class = 'ruff_roots seedling';
												if($displayName == 'sprouts') $class = 'ruff_roots sprouts';
												if($displayName == 'stump') $class = 'ruff_roots stump';
												if($displayName == 'stalk') $class = 'ruff_roots stalk';
												if(strtolower($product_sku_array[$count]) == 'yaky_yam_lotsa_chicken') $class="lotsa-chicken";
												else if(strtolower($product_sku_array[$count]) == 'yaky_yam_very_veggie') $class="very-veggy";
												else if(strtolower($product_sku_array[$count]) == 'yaky_yam_fruity_fruit') $class="fruity-fruit";
											?>										
											<li class="<?php echo $class?>"><a href="javascript:;"><?php echo $displayName?></a>
											<?php $dog_size = $productModel->getProductAttributeByCode($product_id_array[$count++],'dog_size');?>
												<?php if($product['psku'] == 'ruff_roots_seedling' or $product['psku'] == 'ruff_roots_sprouts' or $product['psku'] == 'ruff_roots_stump' or $product['psku'] == 'ruff_roots_stalk'):?>
													<?php if($dog_size != '65 lbs & over'):?>
														<p>for dogs<br>under <?php echo $dog_size;?></p>
													<?php else:?>
														<p>for dogs<br><?php echo $dog_size;?></p>
													<?php endif;?>
											<?php endif;?>
											</li>
										<?php endforeach;?>
									<?php else:?>
										<?php $yaky_yam_array = array();?>
										<?php $yaky_sku_array = array();?>
										<?php $count = 0;?>
										<?php $yam_count = 3;?>
										<?php foreach($display_name_array as $displayName):?>
											<?php if(strtolower($product_sku_array[$count] == 'yaky_yam_lotsa_chicken')) 
											{
												$yaky_yam_array[0] = $displayName;
												$yaky_sku_array[0] = 'lotsa-chicken';
											}
											else if(strtolower($product_sku_array[$count] == 'yaky_yam_very_veggie')) 
												{
													$yaky_yam_array[1] = $displayName;
													$yaky_sku_array[1] = 'very-veggy';
												}
											else if(strtolower($product_sku_array[$count] == 'yaky_yam_fruity_fruit')) 
												{
												$yaky_yam_array[2] = $displayName;
												$yaky_sku_array[2] = 'fruity-fruit';
												}
											else $yaky_yam_array[$yam_count++] = $displayName;
											$count++;
											?>
										<?php endforeach;?>
										<?php $count = 0;?>
										<?php for($i = 0; $i<count($yaky_yam_array); $i++):?>
											<li class="<?php echo $yaky_sku_array[$i]?>"><a href="javascript:;"><?php echo $yaky_yam_array[$i]?></a></li>
										<?php endfor;?>
									<?php endif;?>
								</ul>
								
								

							</div>
						<?php endif;?>
						<div class="products">
							<ul class="slides">
							<?php if($view_category['cat_slug'] != 'ruff_roots'):?>

								<?php if(strtolower($view_category['cat_slug']) == 'yaky-yams'):?>
									<li class="no-color">
										<div class="product">
											<?php $cat_image = getModel('category')->getCategoryBySlug('yaky-yams')['category_image']; $cat_image = getFlickrCategoryImage($cat_image);?>
											<img src="<?php echo $cat_image?>"/>
											<div class="category-detail clearfix">
											<p class="test"></p>
											</div>
										</div>
									</li>
								<?php endif;?>
								<?php foreach($view_products as $product):?>
									<?php $product_id = $product['pid'];?>
									<?php $productModel = getModel('products');?>
									<?php $displayName =  $productModel->getProductAttributeByCode($product_id,'display_name');?>
									<?php if($displayName == false) $displayName = $product['pname'];?>
									<?php
									$class = null;
									if($displayName == '15 lbs') $class = 'blue';
									if($displayName == '70 lbs') $class="grey";
									if($displayName == '35 lbs') $class = "green";
									if($displayName == '55 lbs') $class = "red";
									if($displayName == '65 lbs') $class = "yellow";
									if($displayName == 'seedling') $class = 'ruff_roots';
									if($displayName == 'sprouts') $class = 'ruff_roots';
									if($displayName == 'stump') $class = 'ruff_roots';
									if($displayName == 'stalk') $class = 'ruff_roots';

									if(strtolower($product['pname']) == 'lotsa chicken') $class="lotsa-chicken";
									if(strtolower($product['pname']) == 'very veggie') $class="very-veggy";
									if(strtolower($product['pname']) == 'fruity fruit') $class="fruity-fruit";
									?>
									<?php if(count($view_products)>1):?>
										<li class="no-color" style="display: list-item;">
										<div class="product">
										<?php $cat_image = $view_category['category_image'];$cat_image = getFlickrCategoryImage($cat_image);?>
											<img src="<?php echo $cat_image?>">
											<div class="category-detail clearfix">
												<?php $des = $productModel->getProductAttributeByCode($view_products[0]['pid'],'ruff_roots_creations_description');?>
												<?php if($des):?>
													<?php echo $des;?>
												<?php endif;?>
											</div>
										</div>
									</li>
									<?php endif;?>
									<li class="<?php echo $class?>">
										<div class="product">
											<?php $thumb = getModel('products')->getThumbnailImage($product_id);?>
											<img src = "<?php echo $thumb?>"/>
											<div class="category-detail clearfix">
												<?php if(!$productModel->isConfigurable($product_id)):?>
													<?php $ing = $productModel->getProductAttributeByCode($product_id,'ingredients');?>
													<?php if($ing):?>
														<p class="test">Ingredients :<span><?php echo $ing?></span></p>
													<?php endif;?>
													<?php $gua = $productModel->getProductAttributeByCode($product_id,'guarantee');?>
													<?php if($gua):?>
														<p class="test">Guaranteed Analysis :<span><?php echo $gua?></span></p>
													<?php endif;?>
												<?php else:?>
													<?php $variations = $productModel->getVariations($product_id);?>
													<?php $ing = $productModel->getProductAttributeByCode($variations[0],'ingredients');?>
													<?php if($ing):?>
														<p class="test">Ingredients :<span><?php echo $ing?></span></p>
													<?php endif;?>
													<?php $gua = $productModel->getProductAttributeByCode($variations[0],'guarantee');?>
													<?php if($gua):?>
														<p class="test">Guaranteed Analysis :<span><?php echo $gua?></span></p>
													<?php endif;?>
												<?php endif;?>
											</div>
										</div>
										<?php if(!$productModel->isConfigurable($product_id)):?>
											<?php $desc = $productModel->getProductAttributeByCode($product_id, 'short_description');?>
											<?php if($desc):?>
												<!-- PRODUCT DETAIL COMMENT-->
												<!-- <div class="product-detail">
													<?php echo $desc;?>
												</div> -->
											<?php endif;?>
										<?php else:?>
											<?php $variations = $productModel->getVariations($product_id);?>
											<?php $desc = $productModel->getProductAttributeByCode($variations[0], 'short_description');?>
											<?php if($desc):?>
												<!-- PRODUCT DETAIL COMMENT-->
<!-- 												<div class="product-detail">
													<?php echo $desc;?>
												</div>
 -->											<?php endif;?>
										<?php endif;?>

									</li>
								<?php endforeach;?>
							<?php else:?>
								<li class="ruff_roots" style="display: list-item;">
										<div class="product">
										<?php $cat_image = $view_category['category_image'];$cat_image = getFlickrCategoryImage($cat_image);?>
											<img src="<?php echo $cat_image?>">
											<div class="category-detail clearfix">
												<?php $des = $productModel->getProductAttributeByCode($view_products[0]['pid'],'ruff_roots_creations_description');?>
												<?php if($des):?>
													<?php echo $des;?>
												<?php endif;?>
											</div>
										</div>
									</li>
								<?php endif;?>
							</ul>
						</div>
						<?php if(!$view_category['cat_slug'] =='yaky-yams'):?>
						<script>
							$('.products .slides > li').hide();
							$('.products .slides > li').first().show();
							$('ul.list li a').click(function(){
								$('ul.list li a').removeClass('active');
								$(this).addClass('active');
								var class_name = ($(this).parent().attr('class'));
								$('.products .slides > li').hide();
								$('.products .slides .'+class_name).show();
							});
						</script>
						<?php elseif($view_category['cat_slug'] =='ruff_roots'):?>
							<script></script>
						<?php else:?>
						<script>
							$('.products .slides > li').hide();
							$('.products .slides > li').first().show();
							$('ul.list li a').click(function(){
								$('ul.list li a').removeClass('active');
								$(this).addClass('active');
								$('ul.list li').css('opacity',1);
								$class_name = $(this).parent().attr('class');
								$('ul.list li.'+$class_name).css('opacity',1);
								var class_name = ($(this).parent().attr('class'));
								$('.products .slides > li').hide();
								$('.products .slides .'+class_name).show();
							});
						</script>
						<?php endif;?>

						<?php if(count($view_products) > 1):?>
						</div>
					<?php endif;?>
				</div>
			<?php endif;?>

<?php else:?>
	<div class="wrapper creationDetail">
		<div class="dog-chews">
			<div class="leftBody">
				<div class="description">
					<h1><?php echo $view_category['category_name']?></h1>
					<?php echo $view_category['category_description'];?>
				</div>
				<div class="actions">
				<?php if($view_category['cat_slug'] == 'dog-chews' or $view_category['cat_slug'] == 'chews-red' or $view_category['cat_slug'] == 'chews-green' or $view_category['cat_slug'] == 'chews-blue' or $view_category['cat_slug'] == 'chews-yellow' or $view_category['cat_slug'] == 'chews-gray'):?>
						<a href="<?php echo URL.'pages/endpieces'?>" class="btn btn-blue" style="padding:15px 0px">what to do<br>with end pieces</a>
				<?php elseif($view_category['cat_slug'] == 'yaky-nugget'):?>
						<a href="<?php echo URL.'pages/endpieces'?>" class="btn btn-blue">microwaving<br>tutorial</a>
				<?php endif;?>
				
				</div>
			</div>
			<?php if(isset($view_products)):?>
				<div class="rightBody">
					<div class="product-list-header">
						<span class="left">FOR DOGS UNDER</span><span class="right"><a href="<?php echo URL.'products/categories'?>"><?php echo $back_to_creations?></a></span>
					</div>

					<?php if(count($view_products) > 0):?>
						<div class="categoryContainer yakystick">
							<div class="product-list">
								<ul class="list">
									<?php $display_name_array = array(); $class_array = array();?>
									<?php foreach($view_products as $product):?>
										<?php $product_id = $product['pid'];?>
										<?php $productModel = getModel('products');?>
										<?php $variations = $productModel->getVariations($product_id);?>
										<?php foreach($variations as $variation):?>
											<?php $variation = $productModel->getProduct($variation);?>
											<?php $class = $variation['psku']?>
											<?php $displayName = $productModel->getProductAttributeByCode($variation['pid'],'display_name'); 
											array_push($display_name_array,$displayName); array_push($class_array,$class);?>
										<?php endforeach;?>
										<?php $count = 0;?>
										<?php $display_name_array = array_reverse($display_name_array); $class_array = array_reverse($class_array);?>
										<?php foreach($class_array as $class):?>
											<li class="<?php echo $class?>"><a href="javascript:;"><?php echo $display_name_array[$count++]?></a></li>
										<?php endforeach;?>
									<?php endforeach;?>
								</ul>
							</div>
						<?php endif;?>
						<div class="products">
							<ul class="slides">
							<li class="no-color">
								<div class="product">
								<?php $cat_image = getModel('category')->getCategoryBySlug('yaky-sticks')['category_image'];$cat_image = getFlickrCategoryImage($cat_image);?>
								<img src="<?php echo $cat_image?>"/>
								<div class="category-detail clearfix">
								<?php $variation = false;?>
								<?php foreach($view_products as $product):?>
									<?php $variation = getModel('products')->getVariations($product['pid'])[0]?>
								<?php endforeach;?>
								<?php if($variation):?>
									<?php $ing = $productModel->getProductAttributeByCode($variation,'ingredients');?>
									<?php if($ing):?>
										<p class="test">Ingredients:<span><?php echo $ing?></span></p>
									<?php endif;?>
									<?php $gua = $productModel->getProductAttributeByCode($variation,'guarantee');?>
									<?php if($gua):?>
										<p class="test">Guaranteed Analysis::<span><?php echo $gua?></span></p>
									<?php endif;?>
								<?php endif;?>
								</div>
								</div>
							</li>
								<?php foreach($view_products as $product):?>
									<?php $product_id = $product['pid'];?>
									<?php $productModel = getModel('products');?>
									<?php $variations = $productModel->getVariations($product_id);?>
									<?php foreach($variations as $variation):?>
										<?php $variation = $productModel->getProduct($variation);?>
										<?php $class = $variation['psku']?>
										<?php $thumb = getModel('products')->getThumbnailImage($variation['pid']);?>

										<li class = "<?php echo $class?>">
											<div class="product">
												<img src = "<?php echo $thumb?>"/>
												<div class="category-detail clearfix">
													<?php $ing = $productModel->getProductAttributeByCode($variation['pid'],'ingredients');?>
													<?php if($ing):?>
														<p class="test">Ingredients:<span><?php echo $ing?></span></p>
													<?php endif;?>
													<?php $gua = $productModel->getProductAttributeByCode($variation['pid'],'guarantee');?>
													<?php if($gua):?>
														<p class="test">Guaranteed Analysis:<span><?php echo $gua?></span></p>
													<?php endif;?>
												</div>
											</div>
											<?php $desc = $productModel->getProductAttributeByCode($variation['pid'], 'short_description');?>
											<?php if($desc):?>
												<!-- PRODUCT DETAIL COMMENT-->
												<!-- <div class="product-detail">
													<?php echo $desc;?>
												</div> -->
											<?php endif;?>
										</li>

									<?php endforeach;?>
								<?php endforeach;?>
							</ul>
						</div>
						<?php if(count($view_products) > 1):?>
						</div>
					<?php endif;?>
				</div>
				<script>
					$('.products .slides > li').hide();
					$('.products .slides > li').first().show();
					$('ul.list li a').click(function(){
						$('ul.list li a').removeClass('active');
						var class_name = ($(this).parent().attr('class'));
						$(this).addClass('active');
						$('.products .slides > li').hide();
						$('.products .slides .'+class_name).show();
					});
				</script>
			<?php endif;?>
		</div>

<?php endif;?>
<?php else:?>
	<div class="wrapper">
		<div class="noproduct">
			<h3>No Products in this category</h3>
		</div>
	</div>
<?php endif;?>