
<!-- FOR CATEGORY DOG CHEWS -->
<script type="text/javascript">
	$('.nav ul li.creation').attr('id','creation-active');
</script>

<?php if($view_category_id == 1):?>
	<div class="wrapper creationDetail">
		<div class="dog-chews">
			<!-- TODO MAKE THIS DYNAMIC -->

			<div class="leftBody">
				<div class="description ">
					<h1>Himalayan Dog Chew</h1>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo velit, luctus non odio eget, pulvinar tempor neque. Donec porta, dolor sed tincidunt aliquam, lacus massa faucibus libero, vel tempor elit risus ac leo. Integer lacinia metus eu enim tincidunt tincidunt. Suspendisse imperdiet aliquam metus a porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque at quam augue. Praesent purus urna, sagittis rutrum dolor ut, malesuada interdum risus. Praesent ornare neque velit, quis luctus nunc viverra non. Vivamus viverra eleifend ipsum ut malesuada.</p>

					<p>In at ornare nisi, sed feugiat velit. Donec id molestie mauris. Praesent at iaculis erat, non adipiscing tortor. Cras sed justo venenatis, ullamcorper elit a, adipiscing metus. Integer ullamcorper, nunc vitae aliquam bibendum, leo neque vestibulum leo, non pellentesque augue urna congue mi. Aenean ac pellentesque augue. Nunc id justo ipsum. Cras tortor erat, posuere tincidunt tellus at, pharetra euismod diam. Cras nisl leo, volutpat vitae libero vel, feugiat dapibus purus.</p>
				</div>
			</div>
			<div class="rightBody">
				<div class="product-list-header">
					<span class="left" >For Dogs Under</span><span class="right"><a href="#">back to creations</a></span>
				</div>
				<div class="categoryContainer">
					<div class="product-list">
						<ul class="list">
							<li class="blue"><a href="javascript:;">15 lbs</a></li>
							<li class="green"><a href="javascript:;">35 lbs</a></li>
							<li class="red"><a href="javascript:;">55 lbs</a></li>
							<li class="yellow"><a href="javascript:;">65 lbs</a></li>
							<li class="grey"><a href="javascript:;">75 lbs</a></li>
						</ul>
					</div>
					<div class="products">
						<ul class="slides">
							<li class="no-color">
								<div class="product">
									<!-- TODO MAKE THIS DYNAMIC -->

									<img src="<?php echo ASSET_URL.'images/chews.png'?>"/>
								</div>
								<div class="category-detail clearfix">
									<p>Ingredients:<span>Yak and Cow milk, Salt, and Lime Juice</span></p>
									<p>Guaranteed Analysis:<span>Crude Protien Min 52.8%, Crude Fat Min 0.9%, Moisture Max 10.2%, Ash Max  6.0%</span></p>
								</div> 
							</li>
							<li class="red" style="display:none">
								<div class="product">
									<!-- <img src="<?php echo ASSET_URL.'images/bag_red.jpg'?>"/> -->
									<img src="http://rojan/himalayan/assets/uploads/products/croppedImg_25061.jpeg" draggable="false">
								</div>
								<div class="category-detai clearfix">
									<p>Ingredients:<span>Yak and Cow milk, Salt, and Lime Juice</span></p>
									<p>Guaranteed Analysis:<span>Crude Protien Min 52.8%, Crude Fat Min 0.9%, Moisture Max 10.2%, Ash Max  6.0%</span></p>
								</div>
							</li>
							<li class="green" style="display:none">
								<div class="product">
									<img src="<?php echo ASSET_URL.'images/bag_green.jpg'?>"/>
								</div>
								<div class="category-detail clearfix">
									<p>Ingredients:<span>Yak and Cow milk, Salt, and Lime Juice</span></p>
									<p>Guaranteed Analysis:<span>Crude Protien Min 52.8%, Crude Fat Min 0.9%, Moisture Max 10.2%, Ash Max  6.0%</span></p>
								</div>
							</li>
							<li class="blue" style="display:none">
								<div class="product">
									<img src="<?php echo ASSET_URL.'images/bag_blue.jpg'?>"/>
								</div>
								<div class="category-detail clearfix">
									<p>Ingredients:<span>Yak and Cow milk, Salt, and Lime Juice</span></p>
									<p>Guaranteed Analysis:<span>Crude Protien Min 52.8%, Crude Fat Min 0.9%, Moisture Max 10.2%, Ash Max  6.0%</span></p>
								</div>
							</li>
							<li class="yellow" style="display:none">
								<div class="product">
									<img src="<?php echo ASSET_URL.'images/bag_yellow.jpg'?>"/>
								</div>
								<div class="category-detail clearfix">
									<p>Ingredients:<span>Yak and Cow milk, Salt, and Lime Juice</span></p>
									<p>Guaranteed Analysis:<span>Crude Protien Min 52.8%, Crude Fat Min 0.9%, Moisture Max 10.2%, Ash Max  6.0%</span></p>
								</div>
							</li>
							<li class="grey" style="display:none">
								<div class="product">
									<img src="<?php echo ASSET_URL.'images/bag_gray.jpg'?>"/>
								</div>
								<div class="category-detail clearfix">
									<p>Ingredients:<span>Yak and Cow milk, Salt, and Lime Juice</span></p>
									<p>Guaranteed Analysis:<span>Crude Protien Min 52.8%, Crude Fat Min 0.9%, Moisture Max 10.2%, Ash Max  6.0%</span></p>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
		$('ul.list li a').click(function(){
			var class_name = ($(this).parent().attr('class'));
			$('.products .slides li').hide();
			$('.products .slides .'+class_name).show();
		});
	</script>
	<!-- DOG CHEW CATEGORY ENDS HERE -->

	<!-- DOG SEASONING CATEGORY STARTS HERE -->
<?php elseif($view_category_id == 2):?>
	<div class="wrapper creationDetail">
		<div class="dog-chews">
			<!-- TODO MAKE THIS DYNAMIC -->
			<div class="leftBody">
				<div class="description">
					<h1>HDC Seasoning</h1>
					<p>
						Our Seasoning is made from the grainy powder of Himalayan Dog Chews which you can sprinkle onto any dog or cat food for pets who just cannot seem to get enough of it. Add a little taste of the Himalayas to all of their food! 
					</p>
				</div>
			</div>
			<div class="rightBody">
				<div class="product-list-header">
					<span class="left">For Dogs Under</span><span class="right"><a href="<?php echo URL.'products/categories'?>">back to creations</a></span>
				</div>
				<div class="products">
					<ul class="slides">
						<li class="seasoning">
							<div class="product">
								<!-- TODO MAKE THIS DYNAMIC -->
								<img src="<?php echo ASSET_URL.'images/seasoning.jpg'?>"/>
							</div>
							<div class="category-detail clearfix">
								<p>Ingredients:<span>100% Yak and Cow Milk, Salt and Lime Juice. </span></p>
								<p>Guaranteed Analysis:<span>Crude Protein Min 52.6%. Crude Fat Min 0.9%. Ash Max 6.0%. Moisture Max 10.2% </span></p>
							</div>
						</li>

					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- DOG SEASONING CATEGORY ENDS HERE -->

	<!-- HDC NUGGETS CATEGORY ENDS HERE -->
<?php elseif($view_category_id == 3):?>
	<div class="wrapper creationDetail">
		<div class="dog-chews">
			<!-- TODO MAKE THIS DYNAMIC -->
			<div class="leftBody">
				<div class="description">
					<h3>HDC Seasoning</h3>
					<p>
						What is Yaky Nugget?

						Yaky Nuggets are little bite sized Himalayan Dog Chews that can be popped/puffed in a microwave and given to dogs to enjoy the cheesy flavor. These can also be boiled for ten to fifteen minutes in water to make them soft and easy to chop into smaller bits that can be served with regular dog food. 

						They are also cut to size for uniformity and are carefully tested for quality before being packaged. 

						Key Features

						Does not stain or stink
						Completely Digestible
						A highly nutritious treat
						Made with 100% natural ingredients
						Lactose-free, gluten-free & grain-free


						Why is it so Special?

						Cheese contains enzymes that help remove plaques from their teeth which eventually discourages tooth decay, gingivitis and bacterial growth. Yaky Puff are easier to chew and dissolves in the dogs mouth, that speeds up the effect of the cheese that Himalayan Dog Chew provide. Moreover, because of the strong smoked flavor, our research have shown that this is by far the best rewarding treats for dogs. 

					</p>
				</div>
			</div>
			<div class="rightBody">
				<div class="product-list-header">
					<span class="left">For Dogs Under</span><span class="right"><a href="<?php echo URL.'products/categories'?>">back to creations</a></span>
				</div>
				<div class="products">
					<ul class="slides">
						<li class="seasoning">
							<div class="product">
								<!-- TODO MAKE THIS DYNAMIC -->

								<img src="<?php echo ASSET_URL.'images/yaky_nuggets.jpg'?>"/>
							</div>
							<div class="category-detail clearfix">
								<p>Ingredients:<span>100% Yak and Cow Milk, Salt and Lime Juice. </span></p>
								<p>Guaranteed Analysis:<span>Crude Protein Min 52.6%. Crude Fat Min 0.9%. Ash Max 6.0%. Moisture Max 10.2% </span></p>
							</div>
						</li>

					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- DOG NUGGETS CATEGORY ENDS HERE -->

	<!-- HDC PUFF CATEGORY STARTS HERE -->
<?php elseif($view_category_id == 4):?>
	<div class="wrapper creationDetail">
		<div class="dog-chews">
			<!-- TODO MAKE THIS DYNAMIC -->
			<div class="leftBody">
				<div class="description">
					<h3>HDC Seasoning</h3>
					<p>
						What is Yaky Puff?

						From the beginning, we have tried numerous ways to utilize leftover Himalayan Dog Chews. After extensive research and hundreds of attempts later, we discovered that when Yaky Nuggets are microwaved, they puff up to about five times their original size. The result is a dog treat that is not too soft and not too hard, while maintaining the same cheesy flavor dogs love! 

						Key Features

						Does not stain or stink
						Completely Digestible
						A highly nutritious treat
						Made with 100% natural ingredients
						Lactose-free, gluten-free & grain-free
						Give 'em the pleasure of Cheese!



						Why is it so Special?

						Cheese contains enzymes that help remove plaques from their teeth which eventually discourages tooth decay, gingivitis and bacterial growth. Yaky Puff are easier to chew and dissolves in the dogs mouth, that speeds up the effect of the cheese that Himalayan Dog Chew provide. Moreover, because of the strong smoked flavor, our research have shown that this is by far the best rewarding treats for dogs. 

					</p>
				</div>
			</div>
			<div class="rightBody">
				<div class="product-list-header">
					<span class="left">For Dogs Under</span><span class="right"><a href="<?php echo URL.'products/categories'?>">back to creations</a></span>
				</div>
				<div class="products">
					<ul class="slides">
						<li class="seasoning">
							<div class="product">
								<!-- TODO MAKE THIS DYNAMIC -->

								<img src="<?php echo ASSET_URL.'images/yPuff2.jpg'?>"/>
							</div>
							<div class="category-detail clearfix">
								<p>Ingredients:<span>100% Yak and Cow Milk, Salt and Lime Juice. </span></p>
								<p>Guaranteed Analysis:<span>Crude Protein Min 52.6%. Crude Fat Min 0.9%. Ash Max 6.0%. Moisture Max 10.2% </span></p>
							</div>
						</li>

					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- DOG PUFF CATEGORY ENDS HERE -->

	<!-- HDC CRUNCH CATEGORY STARTS HERE -->
<?php elseif($view_category_id == 5):?>
	<div class="wrapper creationDetail">
		<div class="dog-chews">
			<!-- TODO MAKE THIS DYNAMIC -->
			<div class="leftBody">
				<div class="description">
					<h3>Yaky Crunch</h3>
					<p>
						Yaky Crunch is made up of bite-sized Yaky Puffs which are made from the same ingredients as Himalayan Dog Chews (yak and/or cow milk, and all natural products). The result is a dog treat that is not too soft and not too hard, while maintaining the same cheesy flavor dogs love! 
					</p>
				</div>
			</div>
			<div class="rightBody">
				<div class="product-list-header">
					<span class="left">For Dogs Under</span><span class="right"><a href="<?php echo URL.'products/categories'?>">back to creations</a></span>
				</div>
				<div class="products">
					<ul class="slides">
						<li class="seasoning">
							<div class="product">
								<!-- TODO MAKE THIS DYNAMIC -->

								<img src="<?php echo ASSET_URL.'images/yaky_crunch.jpg'?>"/>
							</div>
							<div class="category-detail clearfix">
								<p>Ingredients:<span>100% Yak and Cow Milk, Salt and Lime Juice. </span></p>
								<p>Guaranteed Analysis:<span>Crude Protein Min 52.6%. Crude Fat Min 0.9%. Ash Max 6.0%. Moisture Max 10.2% </span></p>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- DOG PUFF CATEGORY ENDS HERE -->

	<!-- YAKY YAMS CATEGORY STARTS HERE -->
<?php elseif($view_category_id == 6):?>
	<div class="wrapper creationDetail">
		<div class="dog-chews">
			<!-- TODO MAKE THIS DYNAMIC -->
			<div class="leftBody">
				<div class="description">
					<h3>Yaky Yam</h3>
					<p>
						What is Yaky Yam?

						Yaky Yam is a baked gluten-free treat made of the same ingredients as Himalayan Dog Chews (100% yak and cow milk, salt, and lime juice) mixed with sweet potato and other healthy nourishing ingredients. Now with more rewarding flavor and nutrition! 


						Key Features

						Completely Digestible
						A highly nutritious treat
						Lasts 5 to 7 times longer than Bully Sticks
						Lactose-free & gluten-free
						Yaky Yam Very Veggie and Yaky Yam Fruity Fruit are grain-free
						Made with 100% natural ingredients
						Available in 4 Oz and 14 Oz Boxes

						Why is it so Special?

						Olfaction is primary special sense among dogs. They have over 220 million olfactory nerves compared to 5 million in that of human. Their superior smelling ability comes from their ability to collect air in a special chamber where the scent molecules accumulates until sufficient concentration is availbale for the dog to identify an odor. Anything that have a strong odor is what they consider great to eat. It is for the same reasons why they go after shoes and shocks. » More on Dog's Sense of Smell

						According to Dr. Stanley Coren, dogs appear to like sweet flavor responded in their taste buds by a chemical called furaneol. This is an evolved physiology becuase in a natural environment dogs frequently supplement their diet of small animals with whatever fruits happen to be available, as they are not really strictly carnivores. Dogs do not have a developed taste bud for salty and sour, and they absolutely dislike the bitter taste. This is the reason why they really enjoy and beg for ice-cream etc. » More on Dog's Sense of Taste

						Yaky Yam has the best of the both senses for the dogs. The strong smell of the smoked cheese and the sweet taste of the sweet potator not only ensure their complete enjoyment, but also gives them the best nutrition available
					</p>
				</div>
			</div>
			<div class="rightBody">
				<div class="product-list-header">
					<span class="left">For Dogs Under</span><span class="right"><a href="#">back to creations</a></span>
				</div>
				<div class="categoryContainer yakyyam">
					<div class="product-list">
						<ul class="list">
							<li class="lotsa-chicken"><a href="javascript:;">Lotsa Chicken</a></li>
							<li class="very-veggy"><a href="javascript:;">Very Veggy</a></li>
							<li class="fruity-fruit"><a href="javascript:;">Fruity Fruit</a></li>
						</ul>
					</div>
					<div class="products">
						<ul class="slides">
						<li class="no-color">
							<div class="product">
								<img src="<?php echo ASSET_URL.'images/very_veggie_box.jpg'?>"/>
							</div>
							<div class="category-detail clearfix">
								<p>Ingredients:<span>Yak & Cow Milk, Sweet Potato, Carrot, Garbanzo Flour, Cabbage, Broccoli, Celery, Green Bean, Flax Seed, Salt and Lime Juice</span></p>
								<p>Guaranteed Analysis:<span>Crude Protein Min 35.10%.
									Crude Fat Min 15.90%.
									Dietary fiber max 5.80%.
									Moisture Max 7.90%.
									Ash Max 3.60% </span></p>
							</div>
						</li>
						<li class="lotsa-chicken"  style="display:none">
							<div class="product">
								<!-- TODO MAKE THIS DYNAMIC -->

								<img src="<?php echo ASSET_URL.'images/lotsa_chicken_box.jpg'?>"/>
							</div>
							<div class="category-detail clearfix">
								<p>Ingredients:<span>Yak & Cow Milk, Sweet Potato, Chicken Powder, Brown Rice flour, Chicken Broth, Salt and Lime Juice</span></p>
								<p>Guaranteed Analysis:<span>Crude Protein Min 35.10%.
									Crude Fat Min 15.90%.
									Dietary fiber max 5.80%.
									Moisture Max 7.90%.
									Ash Max 3.60%</span></p>
							</div>
						</li>
						<li class="very-veggy" style="display:none">
							<div class="product">
							<img src="<?php echo ASSET_URL.'images/very_veggie_box.jpg'?>"/>
							</div>
							<div class="category-detail clearfix">
								<p>Ingredients:<span>Yak & Cow Milk, Sweet Potato, Carrot, Garbanzo Flour, Cabbage, Broccoli, Celery, Green Bean, Flax Seed, Salt and Lime Juice</span></p>
								<p>Guaranteed Analysis:<span>Crude Protein Min 35.10%.
									Crude Fat Min 15.90%.
									Dietary fiber max 5.80%.
									Moisture Max 7.90%.
									Ash Max 3.60% </span></p>
							</div>
						</li>
						<li class="fruity-fruit" style="display:none">
							<div class="product">
								<img src="<?php echo ASSET_URL.'images/fruity_fruit_box.jpg'?>"/>
							</div>
							<div class="category-detail clearfix">
								<p>Ingredients:<span>Yak & Cow Milk, Sweet Potato, Banana, Garbanzo Flour, Apple, Pear, Blueberries, Flax Seed, Salt and Lime Juice</span></p>
								<p>Guaranteed Analysis:<span>Crude Protein Min 30.1%.
									Crude Fat Min 5.8%.
									Dietary fiber max 1.3%.
									Moisture Max 16.7%.
									Ash Max 3.80% 
								</span></p>
							</div>
						</li>
						</ul>
					</div>
				</div>
				</div>
			</div>
						</div>
						<script>
							$('ul.list li a').click(function(){
								var class_name = ($(this).parent().attr('class'));
								$('.products .slides li').hide();
								$('.products .slides .'+class_name).show();
							});
						</script>
						<!-- YAKY YAMS CATEGORY ENDS HERE -->

						<!-- YAKY STICKS CATEGORY STARTS HERE -->
					<?php elseif($view_category_id == 7):?>
						<div class="wrapper creationDetail">
							<div class="dog-chews">
								<!-- TODO MAKE THIS DYNAMIC -->
								<div class="leftBody">
									<div class="description">
										<h3>Yaky Sticks</h3>
										<p>
											What is Yaky Stick?

											Yaky Stick is the combination of two of dogs’ favorite treats; Himalayan Dog Chews wrapped around a Bully Stick, which is made using patented processes without using any binding agents or glue in the USA. Bully Sticks come from all free-range grass fed cattle and provide dogs with essential proteins while Himalayan Dog Chews provide them with essential minerals. Moreover, this combination allows the Bully Stick to have little or no saliva from the dogs, hence emitting very low or no odor. While some dogs go for the cheese of Himalayan Dog Chews and some go for the Bully Sticks, we guarantee that any dog will go for Yaky Sticks, enjoying them fairly longer than a regular Bully Stick. 

											Key Features

											Low odor
											Completely Digestible
											Combination of Cheese and Beef
											Made with 100% natural ingredients
											Crumbles of cheese can be microwaved for 20 - 40 seconds (depnding on the type of microwave) to make Yaky Crunch
											Lactose-free, gluten-free & grain-free
											A highly nutritious treat
										</p>
									</div>
								</div>
								<div class="rightBody">
									<div class="product-list-header">
										<span class="left">For Dogs Under</span><span class="right"><a href="#">back to creations</a></span>
									</div>
									<div class="categoryContainer yakystick">
										<div class="product-list">
											<ul class="list">
												<li class="stick-6"><a href="javascript:;">25 lbs</a></li>
												<li class="stick-12"><a href="javascript:;">50 lbs</a></li>
											</ul>
										</div>
										<div class="products">
											<ul class="slides">
												<li class="no-color">
													<div class="product">
														<!-- TODO MAKE THIS DYNAMIC -->
														<img src="<?php echo ASSET_URL.'images/yaky_stick_12_box.jpg'?>"/>
													</div>
													<div class="category-detail clearfix">
														<p>Ingredients:<span>100% Yak and Cow Milk, Beef, Salt and Lime Juice. </span></p>
														<p>Guaranteed Analysis:<span>Crude Protein Min 78.7%. Crude Fat Min 5.7%. Crude Fiber Max 1.0%. Ash Max 3.4%. Moisture Max 10.2% 
														</span></p>
													</div>
												</li>
												<li class="stick-6"  style="display:none">
													<div class="product">
														<!-- TODO MAKE THIS DYNAMIC -->
														<img src="<?php echo ASSET_URL.'images/yaky_stick_6_box.jpg'?>"/>
													</div>
													<div class="category-detail clearfix">
														<p>Ingredients:<span>100% Yak and Cow Milk, Beef, Salt and Lime Juice. </span></p>
														<p>Guaranteed Analysis:<span>Crude Protein Min 78.7%. Crude Fat Min 5.7%. Crude Fiber Max 1.0%. Ash Max 3.4%. Moisture Max 10.2% 
														</span></p>
													</div>
												</li>
												<li class="stick-12" style="display:none">
													<div class="product">
														<img src="<?php echo ASSET_URL.'images/yaky_stick_12_box.jpg'?>"/>
													</div>
													<div class="category-detail clearfix">
														<p>Ingredients:<span>100% Yak and Cow Milk, Beef, Salt and Lime Juice. 
														</span></p>
														<p>Guaranteed Analysis:<span>Crude Protein Min 78.7%. Crude Fat Min 5.7%. Crude Fiber Max 1.0%. Ash Max 3.4%. Moisture Max 10.2% 
														</span></p>
													</div>
												</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
						</div>
						<script>
							$('ul.list li a').click(function(){
								var class_name = ($(this).parent().attr('class'));
								$('ul.list li a').removeClass('active');
								$(this).addClass('active');
								$('.products .slides li').hide();
								$('.products .slides .'+class_name).show();
							});
						</script>
						<!-- YAKY YAMS CATEGORY ENDS HERE -->


					<?php else:?>
					<?php endif;?>