<div class="page-wrapper">
<?php if(isset($view_messages)):?>
<table class="grid">
<thead>
	<th>ID</th>
	<th>Sender Name</th>
	<th>Sender Email</th>
	<th>Nature of Message</th>
	<th>Action</th>
</thead>
<tbody>
<?php foreach($view_messages as $message):?>
	<tr>
		<td><a href="<?php echo ADMIN_URL.'contacts/view/'.$message['contact_id']?>"><?php echo $message['contact_id']?></a></td>
		<td><a href="<?php echo ADMIN_URL.'contacts/view/'.$message['contact_id']?>"><?php echo $message['sender_name']?></a></td>
		<td><a href="<?php echo ADMIN_URL.'contacts/view/'.$message['contact_id']?>"><?php echo $message['sender_email']?></a></td>
		<td><a href="<?php echo ADMIN_URL.'contacts/view/'.$message['contact_id']?>"><?php echo $message['message_nature']?></a></td>
		<td><a class="button" href="<?php echo ADMIN_URL.'contacts/delete/'.$message['contact_id']?>">Delete</a></td>
	</tr>
<?php endforeach;?>
</tbody>
</table>
<?php
$page = getParam('p');
if(!$page) $page = 1;
loadHelper('pagination');
showPagination($page, $view_pagination_num, 'admin/contacts/index');
?>
<?php endif;?>
</div>